noone@mail.com
Analysis of Dieting study 16S data
% Fri Sep  7 05:46:18 2018


Set of analysis routines is applied
                   in nested loops over combinations of defined subsets of samples (if any) and 
                   taxonomic levels. For each output, look for the nearest
                   headers to figure out its place in the report hierarchy.
                   The entire analysis is typically split into sub-reports linked
                   from higher-level pages. Follow links called 'Subreport'.
                   If viewing HTML formatted report, you can click on the
                   images to view the hi-resolution picture. To make it easier to
                   extract pictures for downstream use, picture files are also
                   reported as direct links in the legends.
                   Various intermediate datasets are also saved as delimited files and reported as 
                   direct links.
                   The HTML report is viewed best with modern versions of Chrome or Firefox browsers.
                   Internet Explorer might fail to show left-pane contents menu.



# \(1\) Iterating over subsets of data




## \(1.1\) Subset: All samples, no aggregation, no tests, only plots

[`Subreport`](./1.1-report.html)


## \(1.2\) Subset: Patient/control samples before diet aggregated by SubjectID

[`Subreport`](./1.2-report.html)


## \(1.3\) Subset: Patient/control samples before diet aggregated by SubjectID Additional tests

[`Subreport`](./1.3-report.html)


## \(1.4\) Subset: Patients' samples at visits 1 (before diet) and 2 (after diet), only paired samples

[`Subreport`](./1.4-report.html)


## \(1.5\) Subset: Patients' samples at visits 1 (before diet) and 2 (after diet), only paired samples Additional tests

[`Subreport`](./1.5-report.html)


## \(1.6\) Subset: Patient samples

[`Subreport`](./1.6-report.html)


## \(1.7\) Subset: Patient samples aggregated as geometric medians post-normalization, split by drug before diet status

[`Subreport`](./1.7-report.html)