noone@mail.com
Analysis of Dieting study 16S data
% Fri Sep  7 05:46:18 2018



#### \(1.5.1.3\) Taxonomic level: 6 of Subset: Patients' samples at visits 1 (before diet) and 2 (after diet), only paired samples Additional tests




##### \(1.5.1.3.1\) Loading counts and metadata

[`Subreport`](./1.5.1.3.1-report.html)


##### \(1.5.1.3.2\) Data analysis



Filtering abundance matrix with arguments [ min_mean                :10, min_quant_incidence_frac:0.25, min_quant_mean_frac     :0.25]. Filtering features


Note that some community richness estimators will not work correctly 
               if provided with abundance-filtered counts


After filtering, left 33 records for 39 features


Wrote counts and metadata for raw counts After final feature filtering to files [`data/1.5.1.3.2.1-323732ce4c6samples.raw.16s.l.6.count.tsv`](data/1.5.1.3.2.1-323732ce4c6samples.raw.16s.l.6.count.tsv),[`data/1.5.1.3.2.1-323732ce4c6samples.raw.16s.l.6.attr.tsv`](data/1.5.1.3.2.1-323732ce4c6samples.raw.16s.l.6.attr.tsv)


Wrote counts and metadata for proportions counts After final feature filtering to files [`data/1.5.1.3.2.1-32375321179samples.proportions.16s.l.6.count.tsv`](data/1.5.1.3.2.1-32375321179samples.proportions.16s.l.6.count.tsv),[`data/1.5.1.3.2.1-32375321179samples.proportions.16s.l.6.attr.tsv`](data/1.5.1.3.2.1-32375321179samples.proportions.16s.l.6.attr.tsv)



##### \(1.5.1.3.2.2\) DESeq2 tests and data normalization



Love MI, Huber W, Anders S (2014). “Moderated estimation of fold change and dispersion for RNA-seq data with DESeq2.” _Genome Biology_, *15*,
550. doi: 10.1186/s13059-014-0550-8 (URL: http://doi.org/10.1186/s13059-014-0550-8).


\(1.5.1.3.2.2.1\) <a name="table.349"></a>[`Table 349.`](#table.349) DESeq2 results for task: Drug.Before.Diet \+ DietStatus;\[ alpha:0.05\]. Full dataset is also saved in a delimited text file (click to download and open e.g. in Excel) [`data/1.5.1.3.2.2.1-323620eb20c.1.5.1.3.2.2.1.a.nam.csv`](data/1.5.1.3.2.2.1-323620eb20c.1.5.1.3.2.2.1.a.nam.csv)




| feature                              | baseMean | log2FoldChange | lfcSE  | stat      | pvalue    | padj     | i.baseMean | baseVar    | allZero | dispGeneEst | dispGeneIter | dispFit | dispersion | dispIter | dispOutlier | dispMAP | Intercept | Drug.Before.Diet\_DrugBefore\_YES\_vs\_DrugBefore\_NO | DietStatus\_before.diet\_vs\_after.diet | SE\_Intercept | SE\_Drug.Before.Diet\_DrugBefore\_YES\_vs\_DrugBefore\_NO | SE\_DietStatus\_before.diet\_vs\_after.diet | WaldStatistic\_Intercept | WaldStatistic\_Drug.Before.Diet\_DrugBefore\_YES\_vs\_DrugBefore\_NO | WaldStatistic\_DietStatus\_before.diet\_vs\_after.diet | WaldPvalue\_Intercept | WaldPvalue\_Drug.Before.Diet\_DrugBefore\_YES\_vs\_DrugBefore\_NO | WaldPvalue\_DietStatus\_before.diet\_vs\_after.diet | betaConv | betaIter | deviance | maxCooks  | replace |
|:-------------------------------------|:---------|:---------------|:-------|:----------|:----------|:---------|:-----------|:-----------|:--------|:------------|:-------------|:--------|:-----------|:---------|:------------|:--------|:----------|:------------------------------------------------------|:----------------------------------------|:--------------|:----------------------------------------------------------|:--------------------------------------------|:-------------------------|:---------------------------------------------------------------------|:-------------------------------------------------------|:----------------------|:------------------------------------------------------------------|:----------------------------------------------------|:---------|:---------|:---------|:----------|:--------|
| Megamonas                            | 49.543   | \-12.42593     | 2.9579 | \-4.20094 | NA        | NA       | 49.543     | 8.097e\+04 | FALSE   | 33.000      | 96           | 3.603   | 33.000     | 8        | FALSE       | 33.000  | 8.0890    | \-26.66327                                            | \-12.42593                              | 2.8201        | 3.0617                                                    | 2.9579                                      | 2.8683                   | \-8.70856                                                            | \-4.20094                                              | 4.127e\-03            | 3.078e\-18                                                        | 2.658e\-05                                          | TRUE     | 100      | 34.68    | 23.08089  | TRUE    |
| Lachnospiracea\_incertae\_sedis      | 93.722   | \-2.41099      | 0.6260 | \-3.85165 | 0.0001173 | 0.003168 | 93.722     | 1.484e\+04 | FALSE   | 1.478       | 10           | 2.896   | 1.516      | 6        | FALSE       | 1.516   | 6.8785    | 0.63418                                               | \-2.41099                               | 0.6028        | 0.6494                                                    | 0.6260                                      | 11.4112                  | 0.97651                                                              | \-3.85165                                              | 3.675e\-30            | 3.288e\-01                                                        | 1.173e\-04                                          | TRUE     | 7        | 342.05   | 0.01942   | FALSE   |
| Escherichia\_Shigella                | 10.700   | 4.94881        | 1.8234 | 2.71398   | 0.0066479 | 0.081976 | 10.700     | 2.365e\+03 | FALSE   | 13.138      | 7            | 6.607   | 12.253     | 8        | FALSE       | 12.253  | 0.2670    | \-2.40629                                             | 4.94881                                 | 1.7582        | 1.8777                                                    | 1.8234                                      | 0.1519                   | \-1.28149                                                            | 2.71398                                                | 8.793e\-01            | 2.000e\-01                                                        | 6.648e\-03                                          | TRUE     | 37       | 95.59    | 1.20361   | TRUE    |
| Roseburia                            | 40.203   | \-1.70011      | 0.6519 | \-2.60796 | 0.0091084 | 0.081976 | 40.203     | 2.707e\+03 | FALSE   | 1.564       | 9            | 4.020   | 1.621      | 9        | FALSE       | 1.621   | 6.1676    | \-0.29386                                             | \-1.70011                               | 0.6251        | 0.6745                                                    | 0.6519                                      | 9.8667                   | \-0.43570                                                            | \-2.60796                                              | 5.803e\-23            | 6.631e\-01                                                        | 9.108e\-03                                          | TRUE     | 6        | 299.56   | 0.09110   | FALSE   |
| Unclassified\_Bacteria               | 32.531   | 1.39144        | 0.6259 | 2.22308   | 0.0262107 | 0.176922 | 32.531     | 5.662e\+03 | FALSE   | 1.410       | 12           | 4.472   | 1.469      | 8        | FALSE       | 1.469   | 4.7367    | \-1.25938                                             | 1.39144                                 | 0.5999        | 0.6454                                                    | 0.6259                                      | 7.8963                   | \-1.95135                                                            | 2.22308                                                | 2.873e\-15            | 5.102e\-02                                                        | 2.621e\-02                                          | TRUE     | 9        | 280.34   | 0.59864   | FALSE   |
| Clostridium\_XlVa                    | 23.073   | 1.21152        | 0.5775 | 2.09785   | 0.0359186 | 0.193960 | 23.073     | 6.405e\+02 | FALSE   | 1.169       | 8            | 5.265   | 1.238      | 9        | FALSE       | 1.238   | 3.8471    | \-0.08647                                             | 1.21152                                 | 0.5578        | 0.5970                                                    | 0.5775                                      | 6.8966                   | \-0.14484                                                            | 2.09785                                                | 5.324e\-12            | 8.848e\-01                                                        | 3.592e\-02                                          | TRUE     | 5        | 270.92   | 0.10891   | FALSE   |
| Unclassified\_Lachnospiraceae        | 146.298  | \-1.08398      | 0.5757 | \-1.88301 | 0.0596988 | 0.268645 | 146.298    | 1.969e\+04 | FALSE   | 1.257       | 9            | 3.172   | 1.297      | 8        | FALSE       | 1.297   | 7.6839    | \-0.04017                                             | \-1.08398                               | 0.5559        | 0.5974                                                    | 0.5757                                      | 13.8233                  | \-0.06724                                                            | \-1.88301                                              | 1.844e\-43            | 9.464e\-01                                                        | 5.970e\-02                                          | TRUE     | 6        | 391.04   | 0.04590   | FALSE   |
| Unclassified\_Burkholderiales        | 3.381    | 4.86602        | 2.9381 | 1.65617   | NA        | NA       | 3.381      | 2.135e\+02 | FALSE   | 33.000      | 12           | 8.597   | 33.000     | 8        | FALSE       | 33.000  | \-1.6310  | \-1.24757                                             | 4.86602                                 | 2.8515        | 3.0449                                                    | 2.9381                                      | \-0.5720                 | \-0.40972                                                            | 1.65617                                                | 5.673e\-01            | 6.820e\-01                                                        | 9.769e\-02                                          | TRUE     | 30       | 45.27    | 60.91321  | TRUE    |
| Akkermansia                          | 19.225   | 3.20502        | 2.1332 | 1.50241   | 0.1329902 | 0.508114 | 19.225     | 5.862e\+03 | FALSE   | 19.836      | 10           | 5.683   | 17.732     | 8        | FALSE       | 17.732  | 0.5773    | 1.85027                                               | 3.20502                                 | 2.0812        | 2.2192                                                    | 2.1332                                      | 0.2774                   | 0.83376                                                              | 1.50241                                                | 7.815e\-01            | 4.044e\-01                                                        | 1.330e\-01                                          | TRUE     | 100      | 120.64   | 1.04802   | FALSE   |
| Erysipelotrichaceae\_incertae\_sedis | 42.943   | 1.42015        | 0.9861 | 1.44016   | NA        | NA       | 42.943     | 2.403e\+04 | FALSE   | 3.773       | 12           | 3.885   | 3.777      | 6        | FALSE       | 3.777   | 4.9693    | \-1.18233                                             | 1.42015                                 | 0.9509        | 1.0217                                                    | 0.9861                                      | 5.2257                   | \-1.15722                                                            | 1.44016                                                | 1.735e\-07            | 2.472e\-01                                                        | 1.498e\-01                                          | TRUE     | 43       | 255.54   | 4.56894   | TRUE    |
| Blautia                              | 56.346   | \-1.04191      | 0.7312 | \-1.42485 | 0.1542012 | 0.508114 | 56.346     | 7.199e\+03 | FALSE   | 2.046       | 11           | 3.361   | 2.080      | 8        | FALSE       | 2.080   | 6.3118    | \-0.06234                                             | \-1.04191                               | 0.7052        | 0.7584                                                    | 0.7312                                      | 8.9500                   | \-0.08220                                                            | \-1.42485                                              | 3.553e\-19            | 9.345e\-01                                                        | 1.542e\-01                                          | TRUE     | 10       | 321.39   | 0.14945   | FALSE   |
| Clostridium\_XVIII                   | 7.857    | 0.96895        | 0.7051 | 1.37423   | 0.1693713 | 0.508114 | 7.857      | 8.544e\+01 | FALSE   | 1.647       | 11           | 6.837   | 1.758      | 11       | FALSE       | 1.758   | 2.6528    | \-0.31739                                             | 0.96895                                 | 0.6774        | 0.7256                                                    | 0.7051                                      | 3.9163                   | \-0.43741                                                            | 1.37423                                                | 8.993e\-05            | 6.618e\-01                                                        | 1.694e\-01                                          | TRUE     | 6        | 205.58   | 0.36865   | FALSE   |
| Ruminococcus                         | 26.883   | \-1.06669      | 0.7834 | \-1.36164 | NA        | NA       | 26.883     | 3.326e\+03 | FALSE   | 2.281       | 11           | 4.904   | 2.346      | 7        | FALSE       | 2.346   | 5.5311    | \-0.60052                                             | \-1.06669                               | 0.7518        | 0.8104                                                    | 0.7834                                      | 7.3570                   | \-0.74102                                                            | \-1.36164                                              | 1.882e\-13            | 4.587e\-01                                                        | 1.733e\-01                                          | TRUE     | 14       | 268.80   | 8.75798   | TRUE    |
| Faecalibacterium                     | 213.858  | \-0.66364      | 0.7225 | \-0.91849 | 0.3583602 | 0.820783 | 213.858    | 5.668e\+04 | FALSE   | 2.004       | 9            | 4.576   | 2.057      | 9        | FALSE       | 2.057   | 8.1369    | \-0.15273                                             | \-0.66364                               | 0.6986        | 0.7503                                                    | 0.7225                                      | 11.6470                  | \-0.20355                                                            | \-0.91849                                              | 2.378e\-31            | 8.387e\-01                                                        | 3.584e\-01                                          | TRUE     | 7        | 409.93   | 0.09230   | FALSE   |
| Lactobacillus                        | 3.450    | \-1.38473      | 1.5128 | \-0.91532 | 0.3600223 | 0.820783 | 3.450      | 1.787e\+02 | FALSE   | 8.094       | 7            | 8.526   | 8.145      | 5        | FALSE       | 8.145   | 3.6550    | \-3.97022                                             | \-1.38473                               | 1.4153        | 1.5450                                                    | 1.5128                                      | 2.5825                   | \-2.56970                                                            | \-0.91532                                              | 9.809e\-03            | 1.018e\-02                                                        | 3.600e\-01                                          | TRUE     | 16       | 99.75    | 0.65955   | FALSE   |
| Unclassified\_Clostridiales          | 47.783   | \-0.50844      | 0.6050 | \-0.84036 | 0.4007062 | 0.820783 | 47.783     | 5.880e\+03 | FALSE   | 1.350       | 9            | 3.673   | 1.397      | 8        | FALSE       | 1.397   | 6.6000    | \-1.49580                                             | \-0.50844                               | 0.5796        | 0.6250                                                    | 0.6050                                      | 11.3864                  | \-2.39317                                                            | \-0.84036                                              | 4.888e\-30            | 1.670e\-02                                                        | 4.007e\-01                                          | TRUE     | 7        | 313.41   | 0.94821   | FALSE   |
| Unclassified\_Firmicutes             | 16.048   | \-0.62635      | 0.7545 | \-0.83016 | 0.4064465 | 0.820783 | 16.048     | 1.275e\+03 | FALSE   | 2.002       | 9            | 6.041   | 2.097      | 10       | FALSE       | 2.097   | 5.0365    | \-1.55759                                             | \-0.62635                               | 0.7159        | 0.7755                                                    | 0.7545                                      | 7.0356                   | \-2.00851                                                            | \-0.83016                                              | 1.984e\-12            | 4.459e\-02                                                        | 4.064e\-01                                          | TRUE     | 10       | 235.93   | 0.22003   | FALSE   |
| Parabacteroides                      | 65.650   | 0.87114        | 1.0906 | 0.79875   | NA        | NA       | 65.650     | 2.674e\+04 | FALSE   | 4.743       | 8            | 3.116   | 4.678      | 8        | FALSE       | 4.678   | 5.0641    | 0.61853                                               | 0.87114                                 | 1.0558        | 1.1328                                                    | 1.0906                                      | 4.7966                   | 0.54601                                                              | 0.79875                                                | 1.614e\-06            | 5.851e\-01                                                        | 4.244e\-01                                          | TRUE     | 23       | 277.18   | 8.55505   | TRUE    |
| Dorea                                | 9.340    | 0.55679        | 0.7105 | 0.78366   | 0.4332384 | 0.820783 | 9.340      | 2.861e\+02 | FALSE   | 1.654       | 11           | 6.718   | 1.776      | 12       | FALSE       | 1.776   | 3.7214    | \-1.55369                                             | 0.55679                                 | 0.6702        | 0.7266                                                    | 0.7105                                      | 5.5525                   | \-2.13839                                                            | 0.78366                                                | 2.817e\-08            | 3.249e\-02                                                        | 4.332e\-01                                          | TRUE     | 8        | 209.75   | 0.85231   | FALSE   |
| Unclassified\_Enterobacteriaceae     | 2.317    | \-1.60321      | 2.1944 | \-0.73058 | NA        | NA       | 2.317      | 4.720e\+01 | FALSE   | 20.179      | 6            | 9.852   | 18.395     | 9        | FALSE       | 18.395  | 2.5518    | \-0.81391                                             | \-1.60321                               | 2.1061        | 2.2714                                                    | 2.1944                                      | 1.2116                   | \-0.35833                                                            | \-0.73058                                              | 2.256e\-01            | 7.201e\-01                                                        | 4.650e\-01                                          | TRUE     | 37       | 84.12    | 10.72764  | TRUE    |
| Flavonifractor                       | 10.281   | 0.48023        | 0.7460 | 0.64375   | 0.5197349 | 0.820783 | 10.281     | 1.823e\+02 | FALSE   | 1.940       | 10           | 6.644   | 2.046      | 9        | FALSE       | 2.046   | 2.6726    | 0.65475                                               | 0.48023                                 | 0.7237        | 0.7734                                                    | 0.7460                                      | 3.6929                   | 0.84659                                                              | 0.64375                                                | 2.217e\-04            | 3.972e\-01                                                        | 5.197e\-01                                          | TRUE     | 9        | 219.08   | 0.31256   | FALSE   |
| Clostridium\_sensu\_stricto          | 11.915   | 0.96461        | 1.5487 | 0.62285   | 0.5333812 | 0.820783 | 11.915     | 7.877e\+02 | FALSE   | 9.543       | 10           | 6.491   | 9.315      | 8        | FALSE       | 9.315   | 1.6412    | 1.96989                                               | 0.96461                                 | 1.5088        | 1.6117                                                    | 1.5487                                      | 1.0878                   | 1.22224                                                              | 0.62285                                                | 2.767e\-01            | 2.216e\-01                                                        | 5.334e\-01                                          | TRUE     | 29       | 154.18   | 1.93483   | FALSE   |
| Prevotella                           | 697.122  | \-0.87339      | 1.5281 | \-0.57155 | 0.5676275 | 0.820783 | 697.122    | 3.528e\+06 | FALSE   | 9.211       | 11           | 10.156  | 9.239      | 7        | FALSE       | 9.239   | 10.0180   | \-0.37953                                             | \-0.87339                               | 1.4787        | 1.5875                                                    | 1.5281                                      | 6.7749                   | \-0.23907                                                            | \-0.57155                                              | 1.245e\-11            | 8.111e\-01                                                        | 5.676e\-01                                          | TRUE     | 100      | 303.43   | 0.08231   | FALSE   |
| Unclassified\_Ruminococcaceae        | 45.514   | 0.35079        | 0.6542 | 0.53617   | 0.5918412 | 0.820783 | 45.514     | 3.146e\+03 | FALSE   | 1.610       | 11           | 3.769   | 1.656      | 9        | FALSE       | 1.656   | 4.7960    | 0.75146                                               | 0.35079                                 | 0.6335        | 0.6793                                                    | 0.6542                                      | 7.5702                   | 1.10627                                                              | 0.53617                                                | 3.726e\-14            | 2.686e\-01                                                        | 5.918e\-01                                          | TRUE     | 7        | 313.70   | 0.14813   | FALSE   |
| Unclassified\_Bacteroidales          | 74.914   | 0.43612        | 0.8694 | 0.50161   | 0.6159435 | 0.820783 | 74.914     | 1.910e\+04 | FALSE   | 2.958       | 11           | 2.982   | 2.959      | 5        | FALSE       | 2.959   | 6.7796    | \-1.45160                                             | 0.43612                                 | 0.8391        | 0.9017                                                    | 0.8694                                      | 8.0797                   | \-1.60982                                                            | 0.50161                                                | 6.492e\-16            | 1.074e\-01                                                        | 6.159e\-01                                          | TRUE     | 20       | 314.65   | 0.33411   | FALSE   |
| Odoribacter                          | 4.264    | \-1.19176      | 2.3820 | \-0.50033 | 0.6168453 | 0.820783 | 4.264      | 1.920e\+02 | FALSE   | 25.850      | 9            | 7.879   | 21.692     | 6        | FALSE       | 21.692  | 3.8764    | \-3.28487                                             | \-1.19176                               | 2.2795        | 2.4597                                                    | 2.3820                                      | 1.7005                   | \-1.33546                                                            | \-0.50033                                              | 8.903e\-02            | 1.817e\-01                                                        | 6.168e\-01                                          | TRUE     | 20       | 81.45    | 4.30361   | TRUE    |
| Gemmiger                             | 11.061   | \-0.52160      | 1.1099 | \-0.46996 | 0.6383865 | 0.820783 | 11.061     | 4.246e\+02 | FALSE   | 4.638       | 13           | 6.574   | 4.719      | 9        | FALSE       | 4.719   | 3.4015    | 0.48378                                               | \-0.52160                               | 1.0707        | 1.1510                                                    | 1.1099                                      | 3.1768                   | 0.42031                                                              | \-0.46996                                              | 1.489e\-03            | 6.743e\-01                                                        | 6.384e\-01                                          | TRUE     | 13       | 197.36   | 3.51174   | FALSE   |
| Sutterella                           | 45.972   | \-0.70741      | 1.7543 | \-0.40323 | NA        | NA       | 45.972     | 1.187e\+04 | FALSE   | 13.008      | 8            | 3.749   | 12.143     | 10       | FALSE       | 12.143  | 5.2171    | 0.98734                                               | \-0.70741                               | 1.6975        | 1.8225                                                    | 1.7543                                      | 3.0735                   | 0.54175                                                              | \-0.40323                                              | 2.116e\-03            | 5.880e\-01                                                        | 6.868e\-01                                          | TRUE     | 100      | 187.18   | 5.22715   | TRUE    |
| Veillonella                          | 13.532   | \-0.45710      | 1.2129 | \-0.37686 | NA        | NA       | 13.532     | 3.711e\+03 | FALSE   | 5.297       | 10           | 6.321   | 5.347      | 10       | FALSE       | 5.347   | 5.1580    | \-3.93569                                             | \-0.45710                               | 1.1407        | 1.2410                                                    | 1.2129                                      | 4.5220                   | \-3.17132                                                            | \-0.37686                                              | 6.126e\-06            | 1.517e\-03                                                        | 7.063e\-01                                          | TRUE     | 29       | 151.83   | 11.49966  | TRUE    |
| Alistipes                            | 111.118  | 0.52783        | 1.4875 | 0.35485   | 0.7226997 | 0.886950 | 111.118    | 4.072e\+04 | FALSE   | 9.219       | 11           | 2.933   | 8.741      | 11       | FALSE       | 8.741   | 6.1561    | 0.51638                                               | 0.52783                                 | 1.4395        | 1.5452                                                    | 1.4875                                      | 4.2767                   | 0.33418                                                              | 0.35485                                                | 1.897e\-05            | 7.382e\-01                                                        | 7.227e\-01                                          | TRUE     | 100      | 269.73   | 3.99058   | TRUE    |
| Enterococcus                         | 39.764   | \-0.56811      | 2.0070 | \-0.28306 | NA        | NA       | 39.764     | 3.152e\+04 | FALSE   | 17.351      | 7            | 4.043   | 15.822     | 10       | FALSE       | 15.822  | 6.9658    | \-3.03096                                             | \-0.56811                               | 1.9373        | 2.0821                                                    | 2.0070                                      | 3.5957                   | \-1.45574                                                            | \-0.28306                                              | 3.236e\-04            | 1.455e\-01                                                        | 7.771e\-01                                          | TRUE     | 100      | 128.97   | 113.99761 | TRUE    |
| Clostridium\_XI                      | 56.763   | 0.27886        | 1.0066 | 0.27703   | 0.7817550 | 0.917712 | 56.763     | 1.619e\+04 | FALSE   | 4.003       | 8            | 3.347   | 3.979      | 7        | FALSE       | 3.979   | 5.7167    | \-0.05772                                             | 0.27886                                 | 0.9733        | 1.0450                                                    | 1.0066                                      | 5.8738                   | \-0.05523                                                            | 0.27703                                                | 4.259e\-09            | 9.560e\-01                                                        | 7.818e\-01                                          | TRUE     | 20       | 291.06   | 1.76208   | FALSE   |
| Unclassified\_Lactobacillales        | 11.308   | \-0.44230      | 2.2863 | \-0.19346 | NA        | NA       | 11.308     | 3.560e\+03 | FALSE   | 23.568      | 9            | 6.550   | 19.452     | 5        | FALSE       | 19.452  | 5.3652    | \-8.59849                                             | \-0.44230                               | 2.1647        | 2.3469                                                    | 2.2863                                      | 2.4785                   | \-3.66375                                                            | \-0.19346                                              | 1.319e\-02            | 2.485e\-04                                                        | 8.466e\-01                                          | TRUE     | 100      | 70.32    | 72.78433  | TRUE    |
| Streptococcus                        | 5.220    | 0.15892        | 0.9239 | 0.17201   | 0.8634286 | 0.948320 | 5.220      | 9.960e\+01 | FALSE   | 2.923       | 11           | 7.411   | 3.066      | 11       | FALSE       | 3.066   | 2.8005    | \-0.77554                                             | 0.15892                                 | 0.8796        | 0.9497                                                    | 0.9239                                      | 3.1837                   | \-0.81659                                                            | 0.17201                                                | 1.454e\-03            | 4.142e\-01                                                        | 8.634e\-01                                          | TRUE     | 26       | 173.48   | 0.05180   | FALSE   |
| Turicibacter                         | 2.110    | 0.27581        | 2.0084 | 0.13733   | NA        | NA       | 2.110      | 4.234e\+01 | FALSE   | 16.174      | 9            | 10.138  | 15.329     | 9        | FALSE       | 15.329  | 1.0512    | \-0.07558                                             | 0.27581                                 | 1.9397        | 2.0814                                                    | 2.0084                                      | 0.5419                   | \-0.03631                                                            | 0.13733                                                | 5.879e\-01            | 9.710e\-01                                                        | 8.908e\-01                                          | TRUE     | 35       | 84.80    | 9.68873   | TRUE    |
| Parasutterella                       | 5.666    | \-0.29977      | 2.9016 | \-0.10331 | 0.9177143 | 0.948320 | 5.666      | 2.351e\+02 | FALSE   | 33.000      | 9            | 7.259   | 33.000     | 5        | FALSE       | 33.000  | 2.8412    | \-0.28988                                             | \-0.29977                               | 2.8031        | 3.0113                                                    | 2.9016                                      | 1.0136                   | \-0.09626                                                            | \-0.10331                                              | 3.108e\-01            | 9.233e\-01                                                        | 9.177e\-01                                          | TRUE     | 29       | 84.38    | 0.54208   | FALSE   |
| Bacteroides                          | 6544.420 | 0.06947        | 0.7615 | 0.09123   | 0.9273117 | 0.948320 | 6544.420   | 1.550e\+08 | FALSE   | 2.295       | 11           | 2.301   | 2.295      | 5        | FALSE       | 2.295   | 11.0937   | 2.01201                                               | 0.06947                                 | 0.7370        | 0.7912                                                    | 0.7615                                      | 15.0525                  | 2.54299                                                              | 0.09123                                                | 3.322e\-51            | 1.099e\-02                                                        | 9.273e\-01                                          | TRUE     | 11       | 616.88   | 1.26516   | FALSE   |
| Clostridium\_IV                      | 16.692   | 0.06393        | 0.9863 | 0.06482   | 0.9483203 | 0.948320 | 16.692     | 1.351e\+03 | FALSE   | 3.640       | 9            | 5.968   | 3.720      | 9        | FALSE       | 3.720   | 2.3359    | 2.17175                                               | 0.06393                                 | 0.9631        | 1.0284                                                    | 0.9863                                      | 2.4254                   | 2.11183                                                              | 0.06482                                                | 1.529e\-02            | 3.470e\-02                                                        | 9.483e\-01                                          | TRUE     | 12       | 217.27   | 0.82883   | FALSE   |





##### \(1.5.1.3.2.3\) Default transformations for further data analysis



Specific methods can override these and use their own normalization.


Count normalization method for data analysis (unless modified by specific methods) : [ drop.features:List of 1,  ..$ :"other", method.args  :List of 1,  ..$ theta:1, method       :"norm.ihs.prop"]


Wrote counts and metadata for raw counts Normalized after default transformations to files [`data/1.5.1.3.2.3-3236434a470samples.raw.16s.l.6.count.tsv`](data/1.5.1.3.2.3-3236434a470samples.raw.16s.l.6.count.tsv),[`data/1.5.1.3.2.3-3236434a470samples.raw.16s.l.6.attr.tsv`](data/1.5.1.3.2.3-3236434a470samples.raw.16s.l.6.attr.tsv)



##### \(1.5.1.3.3\) Ordinations, 

[`Subreport`](./1.5.1.3.3-report.html)