noone@mail.com
Analysis of Dieting study 16S data
% Fri Sep  7 05:46:18 2018



#### \(1.5.1.2\) Taxonomic level: 4 of Subset: Patients' samples at visits 1 (before diet) and 2 (after diet), only paired samples Additional tests




##### \(1.5.1.2.1\) Loading counts and metadata

[`Subreport`](./1.5.1.2.1-report.html)


##### \(1.5.1.2.2\) Data analysis



Filtering abundance matrix with arguments [ min_mean                :10, min_quant_incidence_frac:0.25, min_quant_mean_frac     :0.25]. Filtering features


Note that some community richness estimators will not work correctly 
               if provided with abundance-filtered counts


After filtering, left 33 records for 12 features


Wrote counts and metadata for raw counts After final feature filtering to files [`data/1.5.1.2.2.1-3234075d454samples.raw.16s.l.4.count.tsv`](data/1.5.1.2.2.1-3234075d454samples.raw.16s.l.4.count.tsv),[`data/1.5.1.2.2.1-3234075d454samples.raw.16s.l.4.attr.tsv`](data/1.5.1.2.2.1-3234075d454samples.raw.16s.l.4.attr.tsv)


Wrote counts and metadata for proportions counts After final feature filtering to files [`data/1.5.1.2.2.1-32340006c03samples.proportions.16s.l.4.count.tsv`](data/1.5.1.2.2.1-32340006c03samples.proportions.16s.l.4.count.tsv),[`data/1.5.1.2.2.1-32340006c03samples.proportions.16s.l.4.attr.tsv`](data/1.5.1.2.2.1-32340006c03samples.proportions.16s.l.4.attr.tsv)



##### \(1.5.1.2.2.2\) DESeq2 tests and data normalization



Love MI, Huber W, Anders S (2014). “Moderated estimation of fold change and dispersion for RNA-seq data with DESeq2.” _Genome Biology_, *15*,
550. doi: 10.1186/s13059-014-0550-8 (URL: http://doi.org/10.1186/s13059-014-0550-8).


\(1.5.1.2.2.2.1\) <a name="table.348"></a>[`Table 348.`](#table.348) DESeq2 results for task: Drug.Before.Diet \+ DietStatus;\[ alpha:0.05\]. Full dataset is also saved in a delimited text file (click to download and open e.g. in Excel) [`data/1.5.1.2.2.2.1-32378276aa9.1.5.1.2.2.2.1.a.nam.csv`](data/1.5.1.2.2.2.1-32378276aa9.1.5.1.2.2.2.1.a.nam.csv)




| feature                  | baseMean | log2FoldChange | lfcSE  | stat     | pvalue     | padj      | i.baseMean | baseVar    | allZero | dispGeneEst | dispGeneIter | dispFit | dispersion | dispIter | dispOutlier | dispMAP | Intercept | Drug.Before.Diet\_DrugBefore\_YES\_vs\_DrugBefore\_NO | DietStatus\_before.diet\_vs\_after.diet | SE\_Intercept | SE\_Drug.Before.Diet\_DrugBefore\_YES\_vs\_DrugBefore\_NO | SE\_DietStatus\_before.diet\_vs\_after.diet | WaldStatistic\_Intercept | WaldStatistic\_Drug.Before.Diet\_DrugBefore\_YES\_vs\_DrugBefore\_NO | WaldStatistic\_DietStatus\_before.diet\_vs\_after.diet | WaldPvalue\_Intercept | WaldPvalue\_Drug.Before.Diet\_DrugBefore\_YES\_vs\_DrugBefore\_NO | WaldPvalue\_DietStatus\_before.diet\_vs\_after.diet | betaConv | betaIter | deviance | maxCooks | replace |
|:-------------------------|:---------|:---------------|:-------|:---------|:-----------|:----------|:-----------|:-----------|:--------|:------------|:-------------|:--------|:-----------|:---------|:------------|:--------|:----------|:------------------------------------------------------|:----------------------------------------|:--------------|:----------------------------------------------------------|:--------------------------------------------|:-------------------------|:---------------------------------------------------------------------|:-------------------------------------------------------|:----------------------|:------------------------------------------------------------------|:----------------------------------------------------|:---------|:---------|:---------|:---------|:--------|
| Lactobacillales          | 260.23   | \-4.5840       | 1.1497 | \-3.9872 | 6.685e\-05 | 0.0006685 | 260.23     | 1.292e\+06 | FALSE   | 5.192       | 15           | 5.192   | 5.192      | 5        | FALSE       | 5.192   | 11.6518   | \-2.9168                                              | \-4.5840                                | 1.1096        | 1.1928                                                    | 1.1497                                      | 10.5012                  | \-2.4454                                                             | \-3.9872                                               | 8.530e\-26            | 0.01447                                                           | 6.685e\-05                                          | TRUE     | 100      | 313.6    | 1.15521  | FALSE   |
| Erysipelotrichales       | 71.46    | 1.7388         | 0.7636 | 2.2772   | 2.278e\-02 | 0.1138849 | 71.46      | 3.847e\+04 | FALSE   | 2.037       | 12           | 3.632   | 2.273      | 11       | FALSE       | 2.273   | 5.4080    | \-0.8699                                              | 1.7388                                  | 0.7388        | 0.7923                                                    | 0.7636                                      | 7.3201                   | \-1.0979                                                             | 2.2772                                                 | 2.479e\-13            | 0.27225                                                           | 2.278e\-02                                          | TRUE     | 14       | 322.3    | 2.93138  | FALSE   |
| Unclassified\_Bacteria   | 38.83    | 1.3198         | 0.6957 | 1.8972   | 5.780e\-02 | 0.1758255 | 38.83      | 8.230e\+03 | FALSE   | 1.583       | 12           | 3.473   | 1.847      | 11       | FALSE       | 1.847   | 5.2081    | \-1.7179                                              | 1.3198                                  | 0.6694        | 0.7193                                                    | 0.6957                                      | 7.7807                   | \-2.3883                                                             | 1.8972                                                 | 7.214e\-15            | 0.01693                                                           | 5.780e\-02                                          | TRUE     | 9        | 285.7    | 0.24180  | FALSE   |
| Selenomonadales          | 84.77    | \-1.7064       | 0.9837 | \-1.7347 | 8.280e\-02 | 0.1758255 | 84.77      | 7.583e\+04 | FALSE   | 3.703       | 12           | 4.211   | 3.789      | 11       | FALSE       | 3.789   | 7.5702    | \-1.3918                                              | \-1.7064                                | 0.9491        | 1.0205                                                    | 0.9837                                      | 7.9758                   | \-1.3638                                                             | \-1.7347                                               | 1.514e\-15            | 0.17264                                                           | 8.280e\-02                                          | TRUE     | 23       | 293.3    | 0.54258  | FALSE   |
| Verrucomicrobiales       | 24.58    | 3.8790         | 2.2730 | 1.7065   | 8.791e\-02 | 0.1758255 | 24.58      | 1.154e\+04 | FALSE   | 20.155      | 13           | 4.858   | 20.155     | 12       | TRUE        | 12.109  | 0.8045    | 1.0796                                                | 3.8790                                  | 2.2184        | 2.3649                                                    | 2.2730                                      | 0.3626                   | 0.4565                                                               | 1.7065                                                 | 7.169e\-01            | 0.64802                                                           | 8.791e\-02                                          | TRUE     | 100      | 121.1    | 0.67248  | FALSE   |
| Enterobacteriales        | 15.66    | 1.7804         | 1.2510 | 1.4232   | NA         | NA        | 15.66      | 5.102e\+03 | FALSE   | 6.458       | 10           | 4.643   | 5.925      | 10       | FALSE       | 5.925   | 3.4954    | \-2.2315                                              | 1.7804                                  | 1.2003        | 1.2911                                                    | 1.2510                                      | 2.9122                   | \-1.7283                                                             | 1.4232                                                 | 3.589e\-03            | 0.08394                                                           | 1.547e\-01                                          | TRUE     | 100      | 159.3    | 58.85396 | TRUE    |
| Clostridiales            | 959.28   | \-0.5383       | 0.5437 | \-0.9902 | 3.221e\-01 | 0.5368311 | 959.28     | 4.659e\+05 | FALSE   | 1.130       | 8            | 1.358   | 1.168      | 11       | FALSE       | 1.168   | 10.4372   | \-0.4677                                              | \-0.5383                                | 0.5260        | 0.5648                                                    | 0.5437                                      | 19.8425                  | \-0.8282                                                             | \-0.9902                                               | 1.280e\-87            | 0.40755                                                           | 3.221e\-01                                          | TRUE     | 5        | 517.4    | 0.02560  | FALSE   |
| Bacteroidales            | 7670.58  | \-0.4963       | 0.7022 | \-0.7068 | 4.797e\-01 | 0.6547585 | 7670.58    | 1.546e\+08 | FALSE   | 1.800       | 12           | 1.800   | 1.952      | 12       | FALSE       | 1.952   | 12.3602   | 1.0858                                                | \-0.4963                                | 0.6796        | 0.7296                                                    | 0.7022                                      | 18.1875                  | 1.4882                                                               | \-0.7068                                               | 6.483e\-74            | 0.13669                                                           | 4.797e\-01                                          | TRUE     | 8        | 641.3    | 0.38604  | FALSE   |
| Rhizobiales              | 14.67    | \-0.6398       | 1.1458 | \-0.5584 | 5.766e\-01 | 0.6547585 | 14.67      | 8.335e\+02 | FALSE   | 5.332       | 14           | 4.386   | 5.082      | 7        | FALSE       | 5.082   | 3.7404    | 0.6262                                                | \-0.6398                                | 1.1092        | 1.1908                                                    | 1.1458                                      | 3.3722                   | 0.5258                                                               | \-0.5584                                               | 7.457e\-04            | 0.59900                                                           | 5.766e\-01                                          | TRUE     | 13       | 201.0    | 1.92216  | FALSE   |
| Unclassified\_Firmicutes | 17.18    | \-0.4042       | 0.8163 | \-0.4951 | 6.205e\-01 | 0.6547585 | 17.18      | 1.112e\+03 | FALSE   | 2.044       | 9            | 4.896   | 2.496      | 9        | FALSE       | 2.496   | 5.1546    | \-1.8632                                              | \-0.4042                                | 0.7792        | 0.8415                                                    | 0.8163                                      | 6.6155                   | \-2.2141                                                             | \-0.4951                                               | 3.703e\-11            | 0.02682                                                           | 6.205e\-01                                          | TRUE     | 10       | 237.6    | 0.03369  | FALSE   |
| Burkholderiales          | 97.97    | \-0.5554       | 1.2420 | \-0.4472 | 6.548e\-01 | 0.6547585 | 97.97      | 4.107e\+04 | FALSE   | 6.517       | 12           | 4.680   | 6.087      | 11       | FALSE       | 6.087   | 5.9623    | 1.2851                                                | \-0.5554                                | 1.2024        | 1.2907                                                    | 1.2420                                      | 4.9585                   | 0.9957                                                               | \-0.4472                                               | 7.103e\-07            | 0.31941                                                           | 6.548e\-01                                          | TRUE     | 100      | 281.3    | 1.51980  | FALSE   |





##### \(1.5.1.2.2.3\) Default transformations for further data analysis



Specific methods can override these and use their own normalization.


Count normalization method for data analysis (unless modified by specific methods) : [ drop.features:List of 1,  ..$ :"other", method.args  :List of 1,  ..$ theta:1, method       :"norm.ihs.prop"]


Wrote counts and metadata for raw counts Normalized after default transformations to files [`data/1.5.1.2.2.3-3235bd67550samples.raw.16s.l.4.count.tsv`](data/1.5.1.2.2.3-3235bd67550samples.raw.16s.l.4.count.tsv),[`data/1.5.1.2.2.3-3235bd67550samples.raw.16s.l.4.attr.tsv`](data/1.5.1.2.2.3-3235bd67550samples.raw.16s.l.4.attr.tsv)



##### \(1.5.1.2.3\) Ordinations, 

[`Subreport`](./1.5.1.2.3-report.html)