noone@mail.com
Analysis of Dieting study 16S data
% Fri Sep  7 05:46:18 2018



#### \(1.5.1.4\) Taxonomic level: otu of Subset: Patients' samples at visits 1 (before diet) and 2 (after diet), only paired samples Additional tests




##### \(1.5.1.4.1\) Loading counts and metadata

[`Subreport`](./1.5.1.4.1-report.html)


##### \(1.5.1.4.2\) Data analysis



Filtering abundance matrix with arguments [ min_mean                :10, min_quant_incidence_frac:0.25, min_quant_mean_frac     :0.25]. Filtering features


Note that some community richness estimators will not work correctly 
               if provided with abundance-filtered counts


After filtering, left 33 records for 102 features


Wrote counts and metadata for raw counts After final feature filtering to files [`data/1.5.1.4.2.1-32314543d80samples.raw.16s.l.otu.count.tsv`](data/1.5.1.4.2.1-32314543d80samples.raw.16s.l.otu.count.tsv),[`data/1.5.1.4.2.1-32314543d80samples.raw.16s.l.otu.attr.tsv`](data/1.5.1.4.2.1-32314543d80samples.raw.16s.l.otu.attr.tsv)


Wrote counts and metadata for proportions counts After final feature filtering to files [`data/1.5.1.4.2.1-3233750eeasamples.proportions.16s.l.otu.count.tsv`](data/1.5.1.4.2.1-3233750eeasamples.proportions.16s.l.otu.count.tsv),[`data/1.5.1.4.2.1-3233750eeasamples.proportions.16s.l.otu.attr.tsv`](data/1.5.1.4.2.1-3233750eeasamples.proportions.16s.l.otu.attr.tsv)



##### \(1.5.1.4.2.2\) DESeq2 tests and data normalization



Love MI, Huber W, Anders S (2014). “Moderated estimation of fold change and dispersion for RNA-seq data with DESeq2.” _Genome Biology_, *15*,
550. doi: 10.1186/s13059-014-0550-8 (URL: http://doi.org/10.1186/s13059-014-0550-8).


\(1.5.1.4.2.2.1\) <a name="table.350"></a>[`Table 350.`](#table.350) DESeq2 results for task: Drug.Before.Diet \+ DietStatus;\[ alpha:0.05\]. Full dataset is also saved in a delimited text file (click to download and open e.g. in Excel) [`data/1.5.1.4.2.2.1-32311f7526f.1.5.1.4.2.2.1.a.nam.csv`](data/1.5.1.4.2.2.1-32311f7526f.1.5.1.4.2.2.1.a.nam.csv)




| feature                                      | baseMean | log2FoldChange | lfcSE  | stat       | pvalue    | padj    | i.baseMean | baseVar    | allZero | dispGeneEst | dispGeneIter | dispFit | dispersion | dispIter | dispOutlier | dispMAP | Intercept  | Drug.Before.Diet\_DrugBefore\_YES\_vs\_DrugBefore\_NO | DietStatus\_before.diet\_vs\_after.diet | SE\_Intercept | SE\_Drug.Before.Diet\_DrugBefore\_YES\_vs\_DrugBefore\_NO | SE\_DietStatus\_before.diet\_vs\_after.diet | WaldStatistic\_Intercept | WaldStatistic\_Drug.Before.Diet\_DrugBefore\_YES\_vs\_DrugBefore\_NO | WaldStatistic\_DietStatus\_before.diet\_vs\_after.diet | WaldPvalue\_Intercept | WaldPvalue\_Drug.Before.Diet\_DrugBefore\_YES\_vs\_DrugBefore\_NO | WaldPvalue\_DietStatus\_before.diet\_vs\_after.diet | betaConv | betaIter | deviance | maxCooks   | replace |
|:---------------------------------------------|:---------|:---------------|:-------|:-----------|:----------|:--------|:-----------|:-----------|:--------|:------------|:-------------|:--------|:-----------|:---------|:------------|:--------|:-----------|:------------------------------------------------------|:----------------------------------------|:--------------|:----------------------------------------------------------|:--------------------------------------------|:-------------------------|:---------------------------------------------------------------------|:-------------------------------------------------------|:----------------------|:------------------------------------------------------------------|:----------------------------------------------------|:---------|:---------|:---------|:-----------|:--------|
| Bacteria.Otu0435                             | 16.2312  | 30.000000      | 2.9580 | 10.141908  | NA        | NA      | 16.2312    | 8.694e\+03 | FALSE   | 33.000      | 2            | 9.543   | 33.000     | 8        | FALSE       | 33.000  | \-23.52003 | \-24.57702                                            | 30.000000                               | 2.8654        | 3.0600                                                    | 2.9580                                      | \-8.208318               | \-8.03176                                                            | 10.141908                                              | 2.243e\-16            | 9.609e\-16                                                        | 3.600e\-24                                          | TRUE     | 100      | 28.27    | 2.643e\+01 | TRUE    |
| Escherichia\_Shigella.Otu2393                | 49.3582  | 7.054357       | 2.0495 | 3.441966   | 0.0005775 | 0.04216 | 49.3582    | 6.488e\+04 | FALSE   | 16.437      | 8            | 10.573  | 15.743     | 9        | FALSE       | 15.743  | 0.73383    | \-4.05216                                             | 7.054357                                | 1.9826        | 2.1160                                                    | 2.0495                                      | 0.370141                 | \-1.91504                                                            | 3.441966                                               | 7.113e\-01            | 5.549e\-02                                                        | 5.775e\-04                                          | TRUE     | 100      | 98.82    | 3.747e\+00 | TRUE    |
| Megamonas.Otu2657                            | 26.2300  | \-9.364361     | 2.9580 | \-3.165827 | NA        | NA      | 26.2300    | 2.264e\+04 | FALSE   | 33.000      | 81           | 10.612  | 33.000     | 5        | FALSE       | 33.000  | 7.17010    | \-26.19066                                            | \-9.364361                              | 2.8203        | 3.0618                                                    | 2.9580                                      | 2.542276                 | \-8.55392                                                            | \-3.165827                                             | 1.101e\-02            | 1.190e\-17                                                        | 1.546e\-03                                          | TRUE     | 100      | 34.50    | 2.307e\+01 | TRUE    |
| Prevotella.Otu2501                           | 39.0285  | \-8.747835     | 2.8550 | \-3.064009 | NA        | NA      | 39.0285    | 4.418e\+04 | FALSE   | 33.000      | 8            | 11.050  | 31.285     | 6        | FALSE       | 31.285  | 8.28320    | \-6.24219                                             | \-8.747835                              | 2.7386        | 2.9632                                                    | 2.8550                                      | 3.024615                 | \-2.10659                                                            | \-3.064009                                             | 2.490e\-03            | 3.515e\-02                                                        | 2.184e\-03                                          | TRUE     | 100      | 77.63    | 5.192e\+01 | TRUE    |
| Bacteroides.Otu0863                          | 162.5589 | 3.506242       | 1.1510 | 3.046256   | NA        | NA      | 162.5589   | 2.195e\+05 | FALSE   | 5.115       | 12           | 8.569   | 5.214      | 7        | FALSE       | 5.214   | 5.40582    | \-1.27334                                             | 3.506242                                | 1.1143        | 1.1953                                                    | 1.1510                                      | 4.851392                 | \-1.06525                                                            | 3.046256                                               | 1.226e\-06            | 2.868e\-01                                                        | 2.317e\-03                                          | TRUE     | 15       | 298.81   | 9.757e\+00 | TRUE    |
| Lachnospiraceae.Otu2512                      | 7.4368   | \-3.419925     | 1.1651 | \-2.935384 | 0.0033314 | 0.12159 | 7.4368     | 3.900e\+02 | FALSE   | 4.554       | 11           | 8.938   | 4.727      | 10       | FALSE       | 4.727   | 4.15485    | \-0.67270                                             | \-3.419925                              | 1.0914        | 1.2016                                                    | 1.1651                                      | 3.806736                 | \-0.55983                                                            | \-2.935384                                             | 1.408e\-04            | 5.756e\-01                                                        | 3.331e\-03                                          | TRUE     | 17       | 145.51   | 3.771e\-01 | TRUE    |
| Bacteroides.Otu2654                          | 245.2678 | 3.664466       | 1.2553 | 2.919241   | NA        | NA      | 245.2678   | 1.188e\+06 | FALSE   | 6.150       | 12           | 7.949   | 6.210      | 6        | FALSE       | 6.210   | 5.49465    | \-1.22247                                             | 3.664466                                | 1.2152        | 1.3038                                                    | 1.2553                                      | 4.521568                 | \-0.93763                                                            | 2.919241                                               | 6.138e\-06            | 3.484e\-01                                                        | 3.509e\-03                                          | TRUE     | 100      | 288.12   | 3.130e\+01 | TRUE    |
| Lachnospiracea\_incertae\_sedis.Otu1990      | 4.7132   | \-3.576162     | 1.3520 | \-2.645088 | 0.0081670 | 0.14175 | 4.7132     | 3.000e\+02 | FALSE   | 6.102       | 7            | 9.401   | 6.314      | 7        | FALSE       | 6.314   | 1.95890    | 1.39647                                               | \-3.576162                              | 1.2870        | 1.4107                                                    | 1.3520                                      | 1.522086                 | 0.98994                                                              | \-2.645088                                             | 1.280e\-01            | 3.222e\-01                                                        | 8.167e\-03                                          | TRUE     | 21       | 114.56   | 7.135e\-01 | TRUE    |
| Bacteroides.Otu1201                          | 84.0143  | 2.573146       | 0.9931 | 2.591146   | 0.0095657 | 0.14175 | 84.0143    | 4.190e\+04 | FALSE   | 3.737       | 12           | 9.156   | 3.861      | 7        | FALSE       | 3.861   | 3.65945    | 1.31640                                               | 2.573146                                | 0.9678        | 1.0336                                                    | 0.9931                                      | 3.781339                 | 1.27364                                                              | 2.591146                                               | 1.560e\-04            | 2.028e\-01                                                        | 9.566e\-03                                          | TRUE     | 11       | 298.08   | 4.224e\-01 | FALSE   |
| Lachnospiracea\_incertae\_sedis.Otu2746      | 3.5104   | \-3.559339     | 1.3764 | \-2.586026 | 0.0097090 | 0.14175 | 3.5104     | 9.577e\+01 | FALSE   | 6.281       | 8            | 10.078  | 6.550      | 8        | FALSE       | 6.550   | 2.52303    | 0.21405                                               | \-3.559339                              | 1.2995        | 1.4293                                                    | 1.3764                                      | 1.941479                 | 0.14976                                                              | \-2.586026                                             | 5.220e\-02            | 8.810e\-01                                                        | 9.709e\-03                                          | TRUE     | 17       | 110.37   | 2.107e\+00 | TRUE    |
| Bacteroidales.Otu1168                        | 12.2960  | 4.991689       | 1.9523 | 2.556833   | NA        | NA      | 12.2960    | 4.158e\+03 | FALSE   | 14.856      | 10           | 9.206   | 14.031     | 9        | FALSE       | 14.031  | 0.52355    | \-3.84182                                             | 4.991689                                | 1.8868        | 2.0123                                                    | 1.9523                                      | 0.277488                 | \-1.90919                                                            | 2.556833                                               | 7.814e\-01            | 5.624e\-02                                                        | 1.056e\-02                                          | TRUE     | 100      | 90.83    | 4.641e\+01 | TRUE    |
| Clostridium\_XlVa.Otu0236                    | 22.5446  | 1.853420       | 0.7435 | 2.492767   | 0.0126752 | 0.15421 | 22.5446    | 2.105e\+03 | FALSE   | 1.962       | 12           | 10.239  | 2.090      | 7        | FALSE       | 2.090   | 3.68018    | \-0.84455                                             | 1.853420                                | 0.7218        | 0.7711                                                    | 0.7435                                      | 5.098386                 | \-1.09525                                                            | 2.492767                                               | 3.426e\-07            | 2.734e\-01                                                        | 1.268e\-02                                          | TRUE     | 8        | 250.57   | 3.054e\-01 | FALSE   |
| Prevotella.Otu1633                           | 230.1775 | \-4.459071     | 1.8412 | \-2.421833 | NA        | NA      | 230.1775   | 1.657e\+06 | FALSE   | 13.317      | 8            | 8.083   | 12.865     | 7        | FALSE       | 12.865  | 9.61375    | \-6.06520                                             | \-4.459071                              | 1.7551        | 1.8976                                                    | 1.8412                                      | 5.477692                 | \-3.19633                                                            | \-2.421833                                             | 4.309e\-08            | 1.392e\-03                                                        | 1.544e\-02                                          | TRUE     | 100      | 134.13   | 1.239e\+02 | TRUE    |
| Erysipelotrichaceae\_incertae\_sedis.Otu0818 | 84.8619  | 2.394993       | 1.0606 | 2.258237   | 0.0239309 | 0.24957 | 84.8619    | 1.273e\+05 | FALSE   | 4.271       | 12           | 9.143   | 4.387      | 8        | FALSE       | 4.387   | 5.31786    | \-2.36286                                             | 2.394993                                | 1.0240        | 1.0996                                                    | 1.0606                                      | 5.193149                 | \-2.14878                                                            | 2.258237                                               | 2.068e\-07            | 3.165e\-02                                                        | 2.393e\-02                                          | TRUE     | 100      | 250.66   | 4.948e\-01 | FALSE   |
| Blautia.Otu2495                              | 17.6852  | \-2.543548     | 1.1384 | \-2.234286 | NA        | NA      | 17.6852    | 4.952e\+03 | FALSE   | 4.527       | 12           | 9.688   | 4.705      | 9        | FALSE       | 4.705   | 6.00923    | \-2.98903                                             | \-2.543548                              | 1.0710        | 1.1670                                                    | 1.1384                                      | 5.610690                 | \-2.56136                                                            | \-2.234286                                             | 2.015e\-08            | 1.043e\-02                                                        | 2.546e\-02                                          | TRUE     | 16       | 173.69   | 9.090e\+00 | TRUE    |
| Roseburia.Otu2728                            | 12.5732  | \-3.531280     | 1.6188 | \-2.181362 | 0.0291567 | 0.26437 | 12.5732    | 2.243e\+03 | FALSE   | 9.875       | 11           | 9.227   | 9.824      | 5        | FALSE       | 9.824   | 5.10132    | \-1.34409                                             | \-3.531280                              | 1.5425        | 1.6742                                                    | 1.6188                                      | 3.307253                 | \-0.80281                                                            | \-2.181362                                             | 9.422e\-04            | 4.221e\-01                                                        | 2.916e\-02                                          | TRUE     | 24       | 132.47   | 4.115e\+00 | FALSE   |
| Lachnospiracea\_incertae\_sedis.Otu0113      | 14.1479  | \-2.100617     | 0.9829 | \-2.137057 | 0.0325934 | 0.26437 | 14.1479    | 7.428e\+02 | FALSE   | 3.459       | 6            | 9.354   | 3.634      | 9        | FALSE       | 3.634   | 4.92137    | \-0.51859                                             | \-2.100617                              | 0.9411        | 1.0193                                                    | 0.9829                                      | 5.229172                 | \-0.50879                                                            | \-2.137057                                             | 1.703e\-07            | 6.109e\-01                                                        | 3.259e\-02                                          | TRUE     | 13       | 209.89   | 4.785e\-01 | FALSE   |
| Bacteroides.Otu1800                          | 3.5759   | 4.230631       | 2.0738 | 2.040042   | NA        | NA      | 3.5759     | 1.327e\+02 | FALSE   | 17.362      | 8            | 10.028  | 16.089     | 7        | FALSE       | 16.089  | \-1.56152  | 0.16745                                               | 4.230631                                | 2.0284        | 2.1523                                                    | 2.0738                                      | \-0.769839               | 0.07780                                                              | 2.040042                                               | 4.414e\-01            | 9.380e\-01                                                        | 4.135e\-02                                          | TRUE     | 20       | 82.10    | 1.709e\+01 | TRUE    |
| Prevotella.Otu1563                           | 14.5869  | 5.787256       | 2.9299 | 1.975261   | NA        | NA      | 14.5869    | 5.966e\+03 | FALSE   | 33.000      | 8            | 9.392   | 33.000     | 9        | FALSE       | 33.000  | 5.21939    | \-10.11023                                            | 5.787256                                | 2.8065        | 3.0256                                                    | 2.9299                                      | 1.859742                 | \-3.34152                                                            | 1.975261                                               | 6.292e\-02            | 8.332e\-04                                                        | 4.824e\-02                                          | TRUE     | 100      | 58.77    | 5.017e\+01 | TRUE    |
| Lachnospiraceae.Otu2222                      | 14.0588  | \-2.759233     | 1.4190 | \-1.944479 | 0.0518377 | 0.34509 | 14.0588    | 1.107e\+03 | FALSE   | 7.580       | 10           | 9.346   | 7.680      | 8        | FALSE       | 7.680   | 5.31553    | \-1.06095                                             | \-2.759233                              | 1.3597        | 1.4700                                                    | 1.4190                                      | 3.909389                 | \-0.72173                                                            | \-1.944479                                             | 9.253e\-05            | 4.705e\-01                                                        | 5.184e\-02                                          | TRUE     | 17       | 166.01   | 1.294e\-01 | FALSE   |
| Bacteroides.Otu2120                          | 26.5775  | \-2.400097     | 1.2352 | \-1.943131 | 0.0520003 | 0.34509 | 26.5775    | 3.263e\+03 | FALSE   | 5.746       | 14           | 10.642  | 5.917      | 10       | FALSE       | 5.917   | 4.94450    | 1.05507                                               | \-2.400097                              | 1.1930        | 1.2863                                                    | 1.2352                                      | 4.144672                 | 0.82025                                                              | \-1.943131                                             | 3.403e\-05            | 4.121e\-01                                                        | 5.200e\-02                                          | TRUE     | 31       | 218.26   | 3.474e\+00 | FALSE   |
| Bacteroides.Otu2625                          | 133.8583 | 2.712805       | 1.4709 | 1.844340   | 0.0651336 | 0.39623 | 133.8583   | 1.208e\+05 | FALSE   | 8.537       | 14           | 8.739   | 8.540      | 5        | FALSE       | 8.540   | 4.94294    | 0.29901                                               | 2.712805                                | 1.4250        | 1.5284                                                    | 1.4709                                      | 3.468734                 | 0.19563                                                              | 1.844340                                               | 5.229e\-04            | 8.449e\-01                                                        | 6.513e\-02                                          | TRUE     | 100      | 262.89   | 1.733e\+00 | FALSE   |
| Bacteroides.Otu2038                          | 151.9750 | 1.888902       | 1.0796 | 1.749563   | NA        | NA      | 151.9750   | 1.619e\+05 | FALSE   | 4.501       | 9            | 8.631   | 4.600      | 9        | FALSE       | 4.600   | 5.89019    | 0.17204                                               | 1.888902                                | 1.0458        | 1.1219                                                    | 1.0796                                      | 5.632369                 | 0.15335                                                              | 1.749563                                               | 1.778e\-08            | 8.781e\-01                                                        | 8.019e\-02                                          | TRUE     | 25       | 326.79   | 2.310e\+01 | TRUE    |
| Prevotella.Otu0773                           | 16.0072  | \-5.043597     | 2.9294 | \-1.721708 | NA        | NA      | 16.0072    | 8.095e\+03 | FALSE   | 33.000      | 17           | 9.522   | 33.000     | 8        | FALSE       | 33.000  | 5.45797    | \-4.22203                                             | \-5.043597                              | 2.8109        | 3.0373                                                    | 2.9294                                      | 1.941726                 | \-1.39008                                                            | \-1.721708                                             | 5.217e\-02            | 1.645e\-01                                                        | 8.512e\-02                                          | TRUE     | 100      | 48.50    | 8.203e\+01 | TRUE    |
| Dorea.Otu1142                                | 19.7212  | 1.705915       | 1.0011 | 1.704104   | 0.0883617 | 0.49469 | 19.7212    | 4.452e\+03 | FALSE   | 3.614       | 13           | 9.909   | 3.782      | 9        | FALSE       | 3.782   | 4.13128    | \-2.53959                                             | 1.705915                                | 0.9601        | 1.0332                                                    | 1.0011                                      | 4.303170                 | \-2.45806                                                            | 1.704104                                               | 1.684e\-05            | 1.397e\-02                                                        | 8.836e\-02                                          | TRUE     | 14       | 202.03   | 1.232e\+00 | FALSE   |
| Bacteroides.Otu1854                          | 9.5090   | 2.417350       | 1.4473 | 1.670237   | 0.0948726 | 0.49469 | 9.5090     | 1.187e\+03 | FALSE   | 7.821       | 10           | 9.017   | 7.897      | 6        | FALSE       | 7.897   | 2.41924    | \-2.09955                                             | 2.417350                                | 1.3935        | 1.4950                                                    | 1.4473                                      | 1.736057                 | \-1.40435                                                            | 1.670237                                               | 8.255e\-02            | 1.602e\-01                                                        | 9.487e\-02                                          | TRUE     | 27       | 134.32   | 1.634e\+00 | FALSE   |
| Prevotella.Otu1803                           | 32.7981  | 4.746918       | 2.9359 | 1.616847   | NA        | NA      | 32.7981    | 3.430e\+04 | FALSE   | 33.000      | 9            | 11.004  | 33.000     | 9        | FALSE       | 33.000  | 6.47072    | \-11.36151                                            | 4.746918                                | 2.8074        | 3.0293                                                    | 2.9359                                      | 2.304894                 | \-3.75049                                                            | 1.616847                                               | 2.117e\-02            | 1.765e\-04                                                        | 1.059e\-01                                          | TRUE     | 100      | 59.58    | 1.016e\+02 | TRUE    |
| Prevotella.Otu1319                           | 29.1682  | 4.580736       | 2.9367 | 1.559846   | NA        | NA      | 29.1682    | 2.711e\+04 | FALSE   | 33.000      | 11           | 10.832  | 33.000     | 10       | FALSE       | 33.000  | 6.30099    | \-11.19188                                            | 4.580736                                | 2.8076        | 3.0298                                                    | 2.9367                                      | 2.244229                 | \-3.69387                                                            | 1.559846                                               | 2.482e\-02            | 2.209e\-04                                                        | 1.188e\-01                                          | TRUE     | 100      | 52.01    | 9.685e\+01 | TRUE    |
| Lachnospiraceae.Otu0790                      | 14.3623  | 1.822064       | 1.1694 | 1.558168   | 0.1191934 | 0.58007 | 14.3623    | 7.112e\+02 | FALSE   | 5.109       | 13           | 9.372   | 5.266      | 9        | FALSE       | 5.266   | 2.39097    | 0.40527                                               | 1.822064                                | 1.1422        | 1.2174                                                    | 1.1694                                      | 2.093233                 | 0.33289                                                              | 1.558168                                               | 3.633e\-02            | 7.392e\-01                                                        | 1.192e\-01                                          | TRUE     | 12       | 195.44   | 1.157e\-01 | FALSE   |
| Bacteroides.Otu2460                          | 18.3414  | 1.498575       | 1.0167 | 1.473958   | 0.1404928 | 0.60823 | 18.3414    | 1.066e\+03 | FALSE   | 3.839       | 11           | 9.757   | 3.991      | 7        | FALSE       | 3.991   | 3.33928    | \-0.14652                                             | 1.498575                                | 0.9884        | 1.0569                                                    | 1.0167                                      | 3.378607                 | \-0.13864                                                            | 1.473958                                               | 7.285e\-04            | 8.897e\-01                                                        | 1.405e\-01                                          | TRUE     | 15       | 223.15   | 5.682e\-01 | FALSE   |
| Prevotella.Otu2327                           | 15.0111  | 4.302860       | 2.9379 | 1.464619   | NA        | NA      | 15.0111    | 7.060e\+03 | FALSE   | 33.000      | 7            | 9.430   | 33.000     | 5        | FALSE       | 33.000  | 5.33052    | \-10.22201                                            | 4.302860                                | 2.8085        | 3.0308                                                    | 2.9379                                      | 1.897981                 | \-3.37269                                                            | 1.464619                                               | 5.770e\-02            | 7.444e\-04                                                        | 1.430e\-01                                          | TRUE     | 100      | 65.02    | 7.101e\+01 | TRUE    |
| Bacteroides.Otu2065                          | 19.7359  | 4.087504       | 2.9054 | 1.406849   | 0.1594722 | 0.60823 | 19.7359    | 1.154e\+04 | FALSE   | 33.000      | 9            | 9.911   | 32.598     | 6        | FALSE       | 32.598  | \-24.11724 | 25.84099                                              | 4.087504                                | 2.8480        | 3.0419                                                    | 2.9054                                      | \-8.468150               | 8.49515                                                              | 1.406849                                               | 2.493e\-17            | 1.977e\-17                                                        | 1.595e\-01                                          | TRUE     | 100      | 65.63    | 5.378e\-06 | TRUE    |
| Lachnospiracea\_incertae\_sedis.Otu0651      | 24.9326  | \-1.815930     | 1.3030 | \-1.393663 | 0.1634193 | 0.60823 | 24.9326    | 4.961e\+03 | FALSE   | 6.357       | 9            | 10.492  | 6.518      | 9        | FALSE       | 6.518   | 3.20965    | 2.42881                                               | \-1.815930                              | 1.2642        | 1.3639                                                    | 1.3030                                      | 2.538840                 | 1.78076                                                              | \-1.393663                                             | 1.112e\-02            | 7.495e\-02                                                        | 1.634e\-01                                          | TRUE     | 20       | 189.97   | 2.479e\-01 | FALSE   |
| Prevotella.Otu1994                           | 2.4803   | 4.035549       | 2.9376 | 1.373780   | 0.1695099 | 0.60823 | 2.4803     | 2.030e\+02 | FALSE   | 33.000      | 2            | 11.213  | 33.000     | 8        | FALSE       | 33.000  | \-3.45832  | 1.74026                                               | 4.035549                                | 2.8555        | 3.0554                                                    | 2.9376                                      | \-1.211100               | 0.56957                                                              | 1.373780                                               | 2.259e\-01            | 5.690e\-01                                                        | 1.695e\-01                                          | TRUE     | 44       | 24.30    | 3.960e\-06 | TRUE    |
| Parabacteroides.Otu1378                      | 13.5336  | 2.508439       | 1.8285 | 1.371856   | 0.1701083 | 0.60823 | 13.5336    | 1.045e\+03 | FALSE   | 13.419      | 9            | 9.303   | 13.039     | 7        | FALSE       | 13.039  | 2.49516    | \-0.77166                                             | 2.508439                                | 1.7729        | 1.8988                                                    | 1.8285                                      | 1.407351                 | \-0.40639                                                            | 1.371856                                               | 1.593e\-01            | 6.845e\-01                                                        | 1.701e\-01                                          | TRUE     | 22       | 140.17   | 2.293e\-01 | FALSE   |
| Bacteroides.Otu2383                          | 1.9297   | 1.317619       | 0.9725 | 1.354875   | 0.1754574 | 0.60823 | 1.9297     | 1.492e\+01 | FALSE   | 2.643       | 8            | 12.310  | 2.949      | 7        | FALSE       | 2.949   | 0.30768    | \-0.25694                                             | 1.317619                                | 0.9677        | 1.0128                                                    | 0.9725                                      | 0.317960                 | \-0.25369                                                            | 1.354875                                               | 7.505e\-01            | 7.997e\-01                                                        | 1.755e\-01                                          | TRUE     | 10       | 119.25   | 1.370e\+00 | TRUE    |
| Bacteroides.Otu1976                          | 2.2521   | 3.910298       | 2.9386 | 1.330657   | 0.1833017 | 0.60823 | 2.2521     | 1.674e\+02 | FALSE   | 33.000      | 2            | 11.603  | 33.000     | 8        | FALSE       | 33.000  | \-3.43498  | 1.69785                                               | 3.910298                                | 2.8560        | 3.0566                                                    | 2.9386                                      | \-1.202706               | 0.55547                                                              | 1.330657                                               | 2.291e\-01            | 5.786e\-01                                                        | 1.833e\-01                                          | TRUE     | 30       | 21.81    | 3.686e\-06 | TRUE    |
| Lachnospiracea\_incertae\_sedis.Otu0778      | 37.1495  | \-1.640865     | 1.2630 | \-1.299228 | 0.1938657 | 0.61531 | 37.1495    | 6.992e\+03 | FALSE   | 6.086       | 10           | 11.067  | 6.247      | 9        | FALSE       | 6.247   | 6.14228    | \-0.59681                                             | \-1.640865                              | 1.2197        | 1.3116                                                    | 1.2630                                      | 5.035766                 | \-0.45501                                                            | \-1.299228                                             | 4.759e\-07            | 6.491e\-01                                                        | 1.939e\-01                                          | TRUE     | 21       | 228.44   | 2.803e\-01 | FALSE   |
| Bacteroides.Otu2520                          | 451.1319 | 1.283610       | 1.0843 | 1.183833   | 0.2364793 | 0.67139 | 451.1319   | 5.438e\+05 | FALSE   | 4.616       | 11           | 5.922   | 4.649      | 8        | FALSE       | 4.649   | 7.95143    | 0.12070                                               | 1.283610                                | 1.0495        | 1.1265                                                    | 1.0843                                      | 7.576451                 | 0.10714                                                              | 1.183833                                               | 3.551e\-14            | 9.147e\-01                                                        | 2.365e\-01                                          | TRUE     | 24       | 397.19   | 7.629e\-02 | FALSE   |
| Bacteroides.Otu0786                          | 37.8761  | \-1.978281     | 1.6889 | \-1.171313 | 0.2414732 | 0.67139 | 37.8761    | 9.360e\+03 | FALSE   | 11.211      | 11           | 11.064  | 11.204     | 5        | FALSE       | 11.204  | 7.21310    | \-2.06082                                             | \-1.978281                              | 1.6307        | 1.7529                                                    | 1.6889                                      | 4.423300                 | \-1.17565                                                            | \-1.171313                                             | 9.720e\-06            | 2.397e\-01                                                        | 2.415e\-01                                          | TRUE     | 100      | 190.25   | 9.682e\-01 | TRUE    |
| Prevotella.Otu0634                           | 6.1379   | 2.172135       | 1.9209 | 1.130798   | NA        | NA      | 6.1379     | 7.052e\+02 | FALSE   | 14.282      | 13           | 9.040   | 13.517     | 9        | FALSE       | 13.517  | 2.67357    | \-5.01816                                             | 2.172135                                | 1.8190        | 1.9696                                                    | 1.9209                                      | 1.469822                 | \-2.54781                                                            | 1.130798                                               | 1.416e\-01            | 1.084e\-02                                                        | 2.581e\-01                                          | TRUE     | 14       | 77.45    | 1.168e\+01 | TRUE    |
| Prevotella.Otu1987                           | 207.0798 | \-2.598249     | 2.3329 | \-1.113757 | 0.2653833 | 0.67139 | 207.0798   | 4.873e\+05 | FALSE   | 23.110      | 8            | 8.270   | 21.521     | 8        | FALSE       | 21.521  | 8.68596    | \-0.54789                                             | \-2.598249                              | 2.2571        | 2.4236                                                    | 2.3329                                      | 3.848279                 | \-0.22606                                                            | \-1.113757                                             | 1.190e\-04            | 8.212e\-01                                                        | 2.654e\-01                                          | TRUE     | 100      | 171.34   | 3.269e\-01 | FALSE   |
| Sutterella.Otu1997                           | 1.2720   | 3.270236       | 2.9454 | 1.110297   | 0.2668710 | 0.67139 | 1.2720     | 3.157e\+01 | FALSE   | 33.000      | 71           | 14.882  | 33.000     | 9        | FALSE       | 33.000  | \-3.27967  | 1.41583                                               | 3.270236                                | 2.8590        | 3.0636                                                    | 2.9454                                      | \-1.147149               | 0.46215                                                              | 1.110297                                               | 2.513e\-01            | 6.440e\-01                                                        | 2.669e\-01                                          | TRUE     | 21       | 32.21    | 3.933e\-06 | TRUE    |
| Faecalibacterium.Otu0067                     | 187.1864 | \-0.855149     | 0.7705 | \-1.109856 | 0.2670609 | 0.67139 | 187.1864   | 9.031e\+04 | FALSE   | 2.243       | 11           | 8.413   | 2.338      | 11       | FALSE       | 2.338   | 8.72355    | \-1.51303                                             | \-0.855149                              | 0.7448        | 0.8001                                                    | 0.7705                                      | 11.712577                | \-1.89105                                                            | \-1.109856                                             | 1.099e\-31            | 5.862e\-02                                                        | 2.671e\-01                                          | TRUE     | 8        | 388.41   | 1.782e\-01 | FALSE   |
| Prevotella.Otu2227                           | 9.1157   | 3.238782       | 2.9406 | 1.101388   | NA        | NA      | 9.1157     | 2.640e\+03 | FALSE   | 33.000      | 100          | 8.993   | 33.000     | 7        | FALSE       | 33.000  | 4.62033    | \-9.51153                                             | 3.238782                                | 2.8100        | 3.0329                                                    | 2.9406                                      | 1.644251                 | \-3.13613                                                            | 1.101388                                               | 1.001e\-01            | 1.712e\-03                                                        | 2.707e\-01                                          | TRUE     | 100      | 37.78    | 6.053e\+01 | TRUE    |
| Bacteroides.Otu0848                          | 138.3538 | 1.028769       | 0.9577 | 1.074158   | 0.2827519 | 0.67139 | 138.3538   | 4.296e\+04 | FALSE   | 3.510       | 9            | 8.711   | 3.618      | 9        | FALSE       | 3.618   | 6.05567    | 0.66728                                               | 1.028769                                | 0.9278        | 0.9954                                                    | 0.9577                                      | 6.526573                 | 0.67037                                                              | 1.074158                                               | 6.729e\-11            | 5.026e\-01                                                        | 2.828e\-01                                          | TRUE     | 12       | 351.15   | 6.399e\-01 | FALSE   |
| Bacteroides.Otu2343                          | 26.7044  | \-1.580095     | 1.5030 | \-1.051314 | 0.2931144 | 0.67139 | 26.7044    | 4.267e\+03 | FALSE   | 8.750       | 12           | 10.652  | 8.842      | 10       | FALSE       | 8.842   | 6.33071    | \-1.64916                                             | \-1.580095                              | 1.4502        | 1.5596                                                    | 1.5030                                      | 4.365407                 | \-1.05743                                                            | \-1.051314                                             | 1.269e\-05            | 2.903e\-01                                                        | 2.931e\-01                                          | TRUE     | 30       | 190.11   | 4.792e\-01 | TRUE    |
| Roseburia.Otu2084                            | 13.5892  | \-0.978648     | 0.9571 | \-1.022530 | 0.3065299 | 0.67139 | 13.5892    | 3.233e\+02 | FALSE   | 3.323       | 13           | 9.307   | 3.486      | 8        | FALSE       | 3.486   | 4.66975    | \-0.80605                                             | \-0.978648                              | 0.9202        | 0.9924                                                    | 0.9571                                      | 5.074776                 | \-0.81223                                                            | \-1.022530                                             | 3.880e\-07            | 4.167e\-01                                                        | 3.065e\-01                                          | TRUE     | 9        | 218.23   | 1.022e\-01 | FALSE   |
| Clostridium\_XI.Otu2681                      | 41.4545  | 1.675115       | 1.6628 | 1.007429   | 0.3137288 | 0.67139 | 41.4545    | 4.057e\+04 | FALSE   | 10.757      | 11           | 10.993  | 10.770     | 5        | FALSE       | 10.770  | 5.08483    | \-3.43519                                             | 1.675115                                | 1.6022        | 1.7227                                                    | 1.6628                                      | 3.173671                 | \-1.99407                                                            | 1.007429                                               | 1.505e\-03            | 4.614e\-02                                                        | 3.137e\-01                                          | TRUE     | 100      | 150.27   | 3.033e\+00 | FALSE   |
| Prevotella.Otu2666                           | 1.2482   | \-2.950296     | 2.9407 | \-1.003274 | 0.3157286 | 0.67139 | 1.2482     | 3.586e\+01 | FALSE   | 33.000      | 7            | 15.027  | 33.000     | 8        | FALSE       | 33.000  | 0.63803    | 0.92184                                               | \-2.950296                              | 2.8450        | 3.0616                                                    | 2.9407                                      | 0.224265                 | 0.30110                                                              | \-1.003274                                             | 8.226e\-01            | 7.633e\-01                                                        | 3.157e\-01                                          | TRUE     | 14       | 45.26    | 1.238e\+00 | TRUE    |
| Bacteroides.Otu2069                          | 10.9940  | \-1.571199     | 1.5859 | \-0.990745 | 0.3218100 | 0.67139 | 10.9940    | 6.045e\+02 | FALSE   | 9.743       | 10           | 9.113   | 9.698      | 6        | FALSE       | 9.698   | 5.10116    | \-1.85515                                             | \-1.571199                              | 1.5237        | 1.6425                                                    | 1.5859                                      | 3.347812                 | \-1.12946                                                            | \-0.990745                                             | 8.145e\-04            | 2.587e\-01                                                        | 3.218e\-01                                          | TRUE     | 22       | 149.68   | 9.971e\-01 | TRUE    |
| Bacteroidales.Otu0696                        | 47.9746  | \-2.655553     | 2.6809 | \-0.990564 | 0.3218987 | 0.67139 | 47.9746    | 5.273e\+04 | FALSE   | 32.530      | 10           | 10.669  | 27.730     | 7        | FALSE       | 27.730  | 7.07897    | \-5.91769                                             | \-2.655553                              | 2.5710        | 2.7718                                                    | 2.6809                                      | 2.753390                 | \-2.13497                                                            | \-0.990564                                             | 5.898e\-03            | 3.276e\-02                                                        | 3.219e\-01                                          | TRUE     | 100      | 88.73    | 3.611e\-01 | FALSE   |
| Parabacteroides.Otu1107                      | 10.0225  | 2.560853       | 2.7788 | 0.921557   | 0.3567599 | 0.72343 | 10.0225    | 1.344e\+03 | FALSE   | 33.000      | 10           | 9.049   | 29.883     | 7        | FALSE       | 29.883  | \-2.65492  | 4.40524                                               | 2.560853                                | 2.7194        | 2.9049                                                    | 2.7788                                      | \-0.976305               | 1.51649                                                              | 0.921557                                               | 3.289e\-01            | 1.294e\-01                                                        | 3.568e\-01                                          | TRUE     | 48       | 76.33    | 2.638e\-01 | FALSE   |
| Bacteroides.Otu0312                          | 3.9589   | 1.805865       | 1.9861 | 0.909250   | NA        | NA      | 3.9589     | 4.156e\+02 | FALSE   | 15.393      | 9            | 9.768   | 14.419     | 6        | FALSE       | 14.419  | 1.73681    | \-4.08518                                             | 1.805865                                | 1.8887        | 2.0396                                                    | 1.9861                                      | 0.919581                 | \-2.00294                                                            | 0.909250                                               | 3.578e\-01            | 4.518e\-02                                                        | 3.632e\-01                                          | TRUE     | 29       | 66.62    | 1.779e\+01 | TRUE    |
| Bacteroides.Otu2216                          | 7.2138   | 2.426325       | 2.7763 | 0.873955   | 0.3821429 | 0.73761 | 7.2138     | 1.451e\+03 | FALSE   | 33.000      | 9            | 8.945   | 29.765     | 7        | FALSE       | 29.765  | \-2.95915  | 4.42867                                               | 2.426325                                | 2.7157        | 2.9029                                                    | 2.7763                                      | \-1.089628               | 1.52563                                                              | 0.873955                                               | 2.759e\-01            | 1.271e\-01                                                        | 3.821e\-01                                          | TRUE     | 24       | 62.77    | 3.970e\-06 | TRUE    |
| Bacteroides.Otu2375                          | 25.9749  | \-0.806964     | 0.9269 | \-0.870620 | 0.3839614 | 0.73761 | 25.9749    | 1.105e\+03 | FALSE   | 3.155       | 14           | 10.589  | 3.319      | 10       | FALSE       | 3.319   | 4.16785    | 1.24226                                               | \-0.806964                              | 0.8993        | 0.9664                                                    | 0.9269                                      | 4.634713                 | 1.28546                                                              | \-0.870620                                             | 3.574e\-06            | 1.986e\-01                                                        | 3.840e\-01                                          | TRUE     | 11       | 256.36   | 3.134e\-01 | FALSE   |
| Enterococcus.Otu1019                         | 35.0203  | 1.693049       | 2.0353 | 0.831858   | NA        | NA      | 35.0203    | 3.610e\+04 | FALSE   | 16.600      | 9            | 11.055  | 16.037     | 7        | FALSE       | 16.037  | 4.85505    | \-4.31951                                             | 1.693049                                | 1.9561        | 2.1057                                                    | 2.0353                                      | 2.481989                 | \-2.05139                                                            | 0.831858                                               | 1.307e\-02            | 4.023e\-02                                                        | 4.055e\-01                                          | TRUE     | 100      | 111.79   | 1.147e\+02 | TRUE    |
| Lachnospiraceae.Otu2599                      | 17.5813  | \-0.731607     | 0.8879 | \-0.823957 | 0.4099638 | 0.76737 | 17.5813    | 1.335e\+03 | FALSE   | 2.795       | 11           | 9.678   | 2.931      | 7        | FALSE       | 2.931   | 5.84618    | \-3.00998                                             | \-0.731607                              | 0.8432        | 0.9136                                                    | 0.8879                                      | 6.933014                 | \-3.29470                                                            | \-0.823957                                             | 4.120e\-12            | 9.853e\-04                                                        | 4.100e\-01                                          | TRUE     | 13       | 217.35   | 9.238e\-02 | FALSE   |
| Prevotella.Otu2602                           | 39.2605  | 2.314512       | 2.9303 | 0.789849   | NA        | NA      | 39.2605    | 4.907e\+04 | FALSE   | 33.000      | 9            | 11.047  | 33.000     | 9        | FALSE       | 33.000  | 6.72952    | \-8.86571                                             | 2.314512                                | 2.8058        | 3.0259                                                    | 2.9303                                      | 2.398392                 | \-2.92994                                                            | 0.789849                                               | 1.647e\-02            | 3.390e\-03                                                        | 4.296e\-01                                          | TRUE     | 100      | 60.22    | 1.065e\+02 | TRUE    |
| Parabacteroides.Otu1736                      | 39.5038  | \-1.184395     | 1.5047 | \-0.787115 | NA        | NA      | 39.5038    | 1.984e\+04 | FALSE   | 8.751       | 10           | 11.042  | 8.861      | 10       | FALSE       | 8.861   | 6.78797    | \-2.57972                                             | \-1.184395                              | 1.4512        | 1.5607                                                    | 1.5047                                      | 4.677335                 | \-1.65297                                                            | \-0.787115                                             | 2.906e\-06            | 9.834e\-02                                                        | 4.312e\-01                                          | TRUE     | 100      | 192.84   | 3.302e\+01 | TRUE    |
| Lachnospiraceae.Otu0898                      | 10.1893  | \-0.724725     | 0.9442 | \-0.767552 | 0.4427536 | 0.80803 | 10.1893    | 3.547e\+02 | FALSE   | 3.211       | 8            | 9.060   | 3.361      | 9        | FALSE       | 3.361   | 4.16601    | \-0.73522                                             | \-0.724725                              | 0.9076        | 0.9789                                                    | 0.9442                                      | 4.590089                 | \-0.75104                                                            | \-0.767552                                             | 4.431e\-06            | 4.526e\-01                                                        | 4.428e\-01                                          | TRUE     | 17       | 204.06   | 1.594e\-01 | FALSE   |
| Bacteroides.Otu1411                          | 3.7141   | \-0.882584     | 1.2462 | \-0.708194 | 0.4788246 | 0.85254 | 3.7141     | 5.969e\+01 | FALSE   | 5.444       | 9            | 9.927   | 5.673      | 7        | FALSE       | 5.673   | 2.08321    | 0.31840                                               | \-0.882584                              | 1.2037        | 1.2996                                                    | 1.2462                                      | 1.730720                 | 0.24500                                                              | \-0.708194                                             | 8.350e\-02            | 8.065e\-01                                                        | 4.788e\-01                                          | TRUE     | 10       | 136.87   | 1.965e\+00 | TRUE    |
| Bacteroides.Otu1260                          | 7.2242   | \-0.609997     | 0.9113 | \-0.669392 | 0.5032453 | 0.85906 | 7.2242     | 9.303e\+01 | FALSE   | 2.878       | 14           | 8.944   | 3.047      | 9        | FALSE       | 3.047   | 2.68624    | 0.67249                                               | \-0.609997                              | 0.8857        | 0.9530                                                    | 0.9113                                      | 3.032880                 | 0.70568                                                              | \-0.669392                                             | 2.422e\-03            | 4.804e\-01                                                        | 5.032e\-01                                          | TRUE     | 8        | 189.11   | 6.426e\-01 | FALSE   |
| Roseburia.Otu1051                            | 22.6655  | \-0.602346     | 0.9057 | \-0.665047 | 0.5060207 | 0.85906 | 22.6655    | 1.390e\+03 | FALSE   | 3.031       | 8            | 10.253  | 3.171      | 7        | FALSE       | 3.171   | 5.24076    | \-0.73632                                             | \-0.602346                              | 0.8738        | 0.9401                                                    | 0.9057                                      | 5.997774                 | \-0.78327                                                            | \-0.665047                                             | 2.000e\-09            | 4.335e\-01                                                        | 5.060e\-01                                          | TRUE     | 15       | 250.42   | 1.102e\-01 | FALSE   |
| Alistipes.Otu1466                            | 38.9410  | 1.208681       | 1.8854 | 0.641091   | NA        | NA      | 38.9410    | 8.134e\+03 | FALSE   | 14.244      | 12           | 11.052  | 13.993     | 6        | FALSE       | 13.993  | 2.89985    | 2.30772                                               | 1.208681                                | 1.8308        | 1.9613                                                    | 1.8854                                      | 1.583905                 | 1.17661                                                              | 0.641091                                               | 1.132e\-01            | 2.394e\-01                                                        | 5.215e\-01                                          | TRUE     | 39       | 183.25   | 8.112e\+00 | TRUE    |
| Bacteroides.Otu2765                          | 69.4857  | 0.569730       | 0.9293 | 0.613081   | 0.5398230 | 0.88913 | 69.4857    | 8.516e\+03 | FALSE   | 3.269       | 14           | 9.465   | 3.395      | 8        | FALSE       | 3.395   | 5.55175    | 0.37296                                               | 0.569730                                | 0.9004        | 0.9659                                                    | 0.9293                                      | 6.165971                 | 0.38611                                                              | 0.613081                                               | 7.005e\-10            | 6.994e\-01                                                        | 5.398e\-01                                          | TRUE     | 11       | 317.27   | 6.727e\-01 | FALSE   |
| Bacteroides.Otu2104                          | 33.2077  | 0.581312       | 0.9962 | 0.583518   | 0.5595444 | 0.88913 | 33.2077    | 2.264e\+03 | FALSE   | 3.709       | 14           | 11.016  | 3.881      | 7        | FALSE       | 3.881   | 4.76106    | \-0.05565                                             | 0.581312                                | 0.9652        | 1.0353                                                    | 0.9962                                      | 4.932817                 | \-0.05375                                                            | 0.583518                                               | 8.105e\-07            | 9.571e\-01                                                        | 5.595e\-01                                          | TRUE     | 11       | 268.59   | 3.505e\-01 | FALSE   |
| Bacteroides.Otu0480                          | 14.5764  | \-1.248049     | 2.1559 | \-0.578899 | NA        | NA      | 14.5764    | 3.298e\+03 | FALSE   | 19.104      | 10           | 9.391   | 17.668     | 10       | FALSE       | 17.668  | 5.86370    | \-5.27234                                             | \-1.248049                              | 2.0573        | 2.2230                                                    | 2.1559                                      | 2.850232                 | \-2.37176                                                            | \-0.578899                                             | 4.369e\-03            | 1.770e\-02                                                        | 5.627e\-01                                          | TRUE     | 28       | 92.13    | 3.623e\+01 | TRUE    |
| Bacteroides.Otu0752                          | 8.4761   | 0.484164       | 0.8434 | 0.574089   | 0.5659076 | 0.88913 | 8.4761     | 1.495e\+02 | FALSE   | 2.261       | 12           | 8.955   | 2.439      | 10       | FALSE       | 2.439   | 0.42063    | 2.93770                                               | 0.484164                                | 0.8860        | 0.9206                                                    | 0.8434                                      | 0.474742                 | 3.19121                                                              | 0.574089                                               | 6.350e\-01            | 1.417e\-03                                                        | 5.659e\-01                                          | TRUE     | 8        | 188.36   | 1.382e\-01 | FALSE   |
| Bacteroides.Otu1669                          | 12.6218  | 0.650837       | 1.1533 | 0.564307   | 0.5725455 | 0.88913 | 12.6218    | 3.411e\+02 | FALSE   | 4.966       | 9            | 9.231   | 5.137      | 10       | FALSE       | 5.137   | 2.99496    | 0.48019                                               | 0.650837                                | 1.1218        | 1.2006                                                    | 1.1533                                      | 2.669872                 | 0.39995                                                              | 0.564307                                               | 7.588e\-03            | 6.892e\-01                                                        | 5.725e\-01                                          | TRUE     | 18       | 204.37   | 3.297e\-01 | FALSE   |
| Gemmiger.Otu0907                             | 10.9348  | 0.629321       | 1.1715 | 0.537172   | 0.5911491 | 0.88913 | 10.9348    | 4.288e\+02 | FALSE   | 5.141       | 14           | 9.109   | 5.290      | 9        | FALSE       | 5.290   | 3.27773    | \-0.27686                                             | 0.629321                                | 1.1355        | 1.2174                                                    | 1.1715                                      | 2.886509                 | \-0.22743                                                            | 0.537172                                               | 3.895e\-03            | 8.201e\-01                                                        | 5.911e\-01                                          | TRUE     | 14       | 188.36   | 3.912e\+00 | TRUE    |
| Bacteroides.Otu2437                          | 30.3456  | \-0.863731     | 1.6678 | \-0.517891 | 0.6045345 | 0.88913 | 30.3456    | 4.808e\+03 | FALSE   | 10.953      | 10           | 10.900  | 10.949     | 4        | FALSE       | 10.949  | 5.40922    | \-0.19466                                             | \-0.863731                              | 1.6132        | 1.7328                                                    | 1.6678                                      | 3.353176                 | \-0.11234                                                            | \-0.517891                                             | 7.989e\-04            | 9.106e\-01                                                        | 6.045e\-01                                          | TRUE     | 100      | 192.93   | 1.150e\+00 | FALSE   |
| Lactobacillus.Otu1332                        | 0.5898   | 1.124736       | 2.1988 | 0.511513   | 0.6089916 | 0.88913 | 0.5898     | 3.536e\+00 | FALSE   | 15.616      | 9            | 24.184  | 17.539     | 6        | FALSE       | 17.539  | \-0.01288  | \-2.67402                                             | 1.124736                                | 2.1189        | 2.2727                                                    | 2.1988                                      | \-0.006079               | \-1.17658                                                            | 0.511513                                               | 9.951e\-01            | 2.394e\-01                                                        | 6.090e\-01                                          | TRUE     | 10       | 61.89    | 3.889e\-02 | FALSE   |
| Bacteroides.Otu2482                          | 8.7409   | 0.974115       | 1.9087 | 0.510359   | NA        | NA      | 8.7409     | 5.143e\+02 | FALSE   | 14.821      | 9            | 8.970   | 14.183     | 8        | FALSE       | 14.183  | 3.48729    | \-1.79628                                             | 0.974115                                | 1.8426        | 1.9794                                                    | 1.9087                                      | 1.892579                 | \-0.90747                                                            | 0.510359                                               | 5.841e\-02            | 3.642e\-01                                                        | 6.098e\-01                                          | TRUE     | 18       | 124.98   | 7.493e\+00 | TRUE    |
| Blautia.Otu2475                              | 50.4892  | \-0.400648     | 0.9024 | \-0.443970 | 0.6570643 | 0.92000 | 50.4892    | 8.885e\+03 | FALSE   | 3.062       | 11           | 10.489  | 3.188      | 11       | FALSE       | 3.188   | 6.48131    | \-1.09437                                             | \-0.400648                              | 0.8718        | 0.9368                                                    | 0.9024                                      | 7.434415                 | \-1.16815                                                            | \-0.443970                                             | 1.050e\-13            | 2.427e\-01                                                        | 6.571e\-01                                          | TRUE     | 11       | 295.62   | 6.299e\-01 | FALSE   |
| Turicibacter.Otu0468                         | 5.0335   | 0.950330       | 2.1579 | 0.440402   | 0.6596459 | 0.92000 | 5.0335     | 3.456e\+02 | FALSE   | 19.494      | 9            | 9.288   | 17.965     | 10       | FALSE       | 17.965  | 2.42675    | \-1.68604                                             | 0.950330                                | 2.0812        | 2.2361                                                    | 2.1579                                      | 1.166051                 | \-0.75400                                                            | 0.440402                                               | 2.436e\-01            | 4.508e\-01                                                        | 6.596e\-01                                          | TRUE     | 20       | 87.21    | 4.240e\+00 | TRUE    |
| Faecalibacterium.Otu0751                     | 46.1734  | \-0.347831     | 0.8109 | \-0.428970 | 0.6679454 | 0.92000 | 46.1734    | 6.579e\+03 | FALSE   | 2.412       | 8            | 10.780  | 2.550      | 7        | FALSE       | 2.550   | 6.69424    | \-2.10683                                             | \-0.347831                              | 0.7808        | 0.8403                                                    | 0.8109                                      | 8.573283                 | \-2.50738                                                            | \-0.428970                                             | 1.006e\-17            | 1.216e\-02                                                        | 6.679e\-01                                          | TRUE     | 9        | 292.00   | 2.788e\-01 | FALSE   |
| Lactobacillales.Otu0504                      | 25.2215  | \-1.141109     | 2.7305 | \-0.417905 | NA        | NA      | 25.2215    | 1.858e\+04 | FALSE   | 33.000      | 11           | 10.520  | 28.297     | 6        | FALSE       | 28.297  | 7.20752    | \-10.09168                                            | \-1.141109                              | 2.6027        | 2.8130                                                    | 2.7305                                      | 2.769230                 | \-3.58751                                                            | \-0.417905                                             | 5.619e\-03            | 3.339e\-04                                                        | 6.760e\-01                                          | TRUE     | 100      | 65.14    | 7.845e\+01 | TRUE    |
| Alistipes.Otu2508                            | 94.9423  | 0.735551       | 1.8737 | 0.392557   | NA        | NA      | 94.9423    | 1.243e\+05 | FALSE   | 14.269      | 8            | 9.023   | 13.867     | 10       | FALSE       | 13.867  | 7.07540    | \-2.32800                                             | 0.735551                                | 1.8124        | 1.9461                                                    | 1.8737                                      | 3.903799                 | \-1.19623                                                            | 0.392557                                               | 9.469e\-05            | 2.316e\-01                                                        | 6.946e\-01                                          | TRUE     | 100      | 205.82   | 4.744e\+00 | TRUE    |
| Bacteroides.Otu2534                          | 3.4141   | 0.860516       | 2.4726 | 0.348024   | 0.7278223 | 0.98391 | 3.4141     | 1.372e\+02 | FALSE   | 27.178      | 8            | 10.156  | 23.455     | 6        | FALSE       | 23.455  | \-1.23977  | 3.15301                                               | 0.860516                                | 2.4248        | 2.5889                                                    | 2.4726                                      | \-0.511284               | 1.21791                                                              | 0.348024                                               | 6.092e\-01            | 2.233e\-01                                                        | 7.278e\-01                                          | TRUE     | 16       | 75.27    | 1.232e\+00 | TRUE    |
| Bacteroides.Otu2416                          | 16.5669  | 0.335200       | 1.1185 | 0.299679   | 0.7644221 | 0.99278 | 16.5669    | 1.993e\+03 | FALSE   | 4.611       | 11           | 9.576   | 4.776      | 10       | FALSE       | 4.776   | 1.98609    | 2.36101                                               | 0.335200                                | 1.1009        | 1.1730                                                    | 1.1185                                      | 1.804085                 | 2.01283                                                              | 0.299679                                               | 7.122e\-02            | 4.413e\-02                                                        | 7.644e\-01                                          | TRUE     | 10       | 203.30   | 4.276e\-01 | FALSE   |
| Bacteroides.Otu0929                          | 150.3538 | 0.337399       | 1.1398 | 0.296011   | 0.7672215 | 0.99278 | 150.3538   | 8.798e\+04 | FALSE   | 5.016       | 11           | 8.641   | 5.119      | 7        | FALSE       | 5.119   | 4.94106    | 2.63916                                               | 0.337399                                | 1.1055        | 1.1856                                                    | 1.1398                                      | 4.469591                 | 2.22603                                                              | 0.296011                                               | 7.837e\-06            | 2.601e\-02                                                        | 7.672e\-01                                          | TRUE     | 16       | 319.06   | 6.153e\-01 | FALSE   |
| Prevotella.Otu0882                           | 1.1136   | \-0.872201     | 2.9480 | \-0.295861 | NA        | NA      | 1.1136     | 4.092e\+01 | FALSE   | 33.000      | 2            | 15.971  | 33.000     | 7        | FALSE       | 33.000  | 1.65218    | \-3.33275                                             | \-0.872201                              | 2.8283        | 3.0512                                                    | 2.9480                                      | 0.584152                 | \-1.09228                                                            | \-0.295861                                             | 5.591e\-01            | 2.747e\-01                                                        | 7.673e\-01                                          | TRUE     | 28       | 20.11    | 1.179e\+01 | TRUE    |
| Bacteroides.Otu0069                          | 93.2839  | \-0.254109     | 0.8897 | \-0.285600 | 0.7751846 | 0.99278 | 93.2839    | 1.568e\+04 | FALSE   | 2.957       | 8            | 9.040   | 3.089      | 9        | FALSE       | 3.089   | 4.21040    | 3.01470                                               | \-0.254109                              | 0.8661        | 0.9282                                                    | 0.8897                                      | 4.861526                 | 3.24773                                                              | \-0.285600                                             | 1.165e\-06            | 1.163e\-03                                                        | 7.752e\-01                                          | TRUE     | 7        | 322.08   | 2.208e\-01 | FALSE   |
| Bacteroides.Otu0877                          | 23.4773  | 0.170114       | 0.9090 | 0.187137   | 0.8515533 | 0.99738 | 23.4773    | 1.600e\+03 | FALSE   | 3.038       | 10           | 10.342  | 3.188      | 8        | FALSE       | 3.188   | 5.27785    | \-1.61390                                             | 0.170114                                | 0.8758        | 0.9420                                                    | 0.9090                                      | 6.026211                 | \-1.71321                                                            | 0.187137                                               | 1.678e\-09            | 8.667e\-02                                                        | 8.516e\-01                                          | TRUE     | 9        | 247.28   | 2.355e\-01 | FALSE   |
| Akkermansia.Otu1935                          | 10.8638  | 0.368049       | 2.1106 | 0.174380   | 0.8615670 | 0.99738 | 10.8638    | 2.299e\+03 | FALSE   | 18.345      | 9            | 9.104   | 16.968     | 9        | FALSE       | 16.968  | 4.45434    | \-4.34022                                             | 0.368049                                | 2.0174        | 2.1775                                                    | 2.1106                                      | 2.207981                 | \-1.99319                                                            | 0.174380                                               | 2.725e\-02            | 4.624e\-02                                                        | 8.616e\-01                                          | TRUE     | 35       | 97.61    | 1.473e\+00 | TRUE    |
| Bacteroides.Otu2431                          | 108.7112 | 0.155288       | 0.9563 | 0.162385   | 0.8710029 | 0.99738 | 108.7112   | 1.824e\+04 | FALSE   | 3.489       | 7            | 8.908   | 3.604      | 8        | FALSE       | 3.604   | 6.17405    | 0.73178                                               | 0.155288                                | 0.9262        | 0.9940                                                    | 0.9563                                      | 6.666310                 | 0.73622                                                              | 0.162385                                               | 2.623e\-11            | 4.616e\-01                                                        | 8.710e\-01                                          | TRUE     | 13       | 341.00   | 1.538e\-01 | FALSE   |
| Bacteroides.Otu2566                          | 3.0055   | 0.232084       | 1.8603 | 0.124759   | 0.9007142 | 0.99738 | 3.0055     | 8.354e\+01 | FALSE   | 13.279      | 9            | 10.539  | 12.893     | 7        | FALSE       | 12.893  | \-1.93887  | 4.06851                                               | 0.232084                                | 1.8417        | 1.9636                                                    | 1.8603                                      | \-1.052763               | 2.07192                                                              | 0.124759                                               | 2.924e\-01            | 3.827e\-02                                                        | 9.007e\-01                                          | TRUE     | 14       | 91.20    | 3.765e\-02 | FALSE   |
| Clostridiales.Otu1597                        | 23.7992  | \-0.356608     | 2.9418 | \-0.121219 | 0.9035172 | 0.99738 | 23.7992    | 8.737e\+03 | FALSE   | 33.000      | 25           | 10.377  | 33.000     | 8        | FALSE       | 33.000  | 6.20022    | \-25.71718                                            | \-0.356608                              | 2.8092        | 3.0335                                                    | 2.9418                                      | 2.207142                 | \-8.47768                                                            | \-0.121219                                             | 2.730e\-02            | 2.297e\-17                                                        | 9.035e\-01                                          | TRUE     | 100      | 59.17    | 3.950e\+00 | FALSE   |
| Sutterella.Otu0171                           | 20.2230  | \-0.228718     | 2.1175 | \-0.108014 | 0.9139847 | 0.99738 | 20.2230    | 2.101e\+03 | FALSE   | 18.572      | 9            | 9.966   | 17.648     | 7        | FALSE       | 17.648  | 5.17250    | \-1.47615                                             | \-0.228718                              | 2.0470        | 2.1987                                                    | 2.1175                                      | 2.526850                 | \-0.67136                                                            | \-0.108014                                             | 1.151e\-02            | 5.020e\-01                                                        | 9.140e\-01                                          | TRUE     | 45       | 136.92   | 4.447e\-02 | FALSE   |
| Clostridium\_XI.Otu1804                      | 103.9307 | 0.105918       | 1.1553 | 0.091679   | 0.9269535 | 0.99738 | 103.9307   | 7.402e\+04 | FALSE   | 5.171       | 9            | 8.944   | 5.266      | 8        | FALSE       | 5.266   | 7.22829    | \-1.09651                                             | 0.105918                                | 1.1176        | 1.2000                                                    | 1.1553                                      | 6.467606                 | \-0.91373                                                            | 0.091679                                               | 9.957e\-11            | 3.609e\-01                                                        | 9.270e\-01                                          | TRUE     | 28       | 294.43   | 8.072e\-01 | FALSE   |
| Bacteroides.Otu0661                          | 95.4326  | 0.103365       | 1.1325 | 0.091270   | 0.9272780 | 0.99738 | 95.4326    | 3.128e\+04 | FALSE   | 4.935       | 9            | 9.018   | 5.048      | 7        | FALSE       | 5.048   | 4.85594    | 2.15264                                               | 0.103365                                | 1.0984        | 1.1781                                                    | 1.1325                                      | 4.421083                 | 1.82716                                                              | 0.091270                                               | 9.821e\-06            | 6.768e\-02                                                        | 9.273e\-01                                          | TRUE     | 19       | 298.64   | 1.288e\+00 | FALSE   |
| Bacteroides.Otu0763                          | 8.5675   | 0.053019       | 0.7546 | 0.070264   | 0.9439834 | 0.99738 | 8.5675     | 1.043e\+02 | FALSE   | 1.795       | 14           | 8.960   | 1.944      | 9        | FALSE       | 1.944   | 1.04875    | 2.55415                                               | 0.053019                                | 0.7802        | 0.8201                                                    | 0.7546                                      | 1.344181                 | 3.11446                                                              | 0.070264                                               | 1.789e\-01            | 1.843e\-03                                                        | 9.440e\-01                                          | TRUE     | 8        | 197.02   | 2.192e\-02 | FALSE   |
| Lachnospiraceae.Otu1734                      | 13.1509  | \-0.063119     | 0.9803 | \-0.064389 | 0.9486605 | 0.99738 | 13.1509    | 2.140e\+03 | FALSE   | 3.437       | 9            | 9.272   | 3.585      | 10       | FALSE       | 3.585   | 4.89016    | \-2.68290                                             | \-0.063119                              | 0.9339        | 1.0098                                                    | 0.9803                                      | 5.236533                 | \-2.65679                                                            | \-0.064389                                             | 1.636e\-07            | 7.889e\-03                                                        | 9.487e\-01                                          | TRUE     | 26       | 193.18   | 1.555e\+00 | FALSE   |
| Bacteroides.Otu0001                          | 771.6104 | \-0.046074     | 0.9702 | \-0.047491 | 0.9621218 | 0.99738 | 771.6104   | 1.178e\+06 | FALSE   | 3.717       | 14           | 3.845   | 3.721      | 6        | FALSE       | 3.721   | 7.54110    | 2.59407                                               | \-0.046074                              | 0.9393        | 1.0082                                                    | 0.9702                                      | 8.028387                 | 2.57288                                                              | \-0.047491                                             | 9.876e\-16            | 1.009e\-02                                                        | 9.621e\-01                                          | TRUE     | 11       | 446.48   | 2.146e\-01 | FALSE   |
| Bacteroides.Otu1624                          | 0.4180   | 0.075191       | 1.8242 | 0.041218   | 0.9671218 | 0.99738 | 0.4180     | 9.533e\-01 | FALSE   | 9.337       | 9            | 31.063  | 11.698     | 9        | FALSE       | 11.698  | \-1.29145  | 0.79774                                               | 0.075191                                | 1.7742        | 1.9037                                                    | 1.8242                                      | \-0.727915               | 0.41904                                                              | 0.041218                                               | 4.667e\-01            | 6.752e\-01                                                        | 9.671e\-01                                          | TRUE     | 8        | 64.13    | 4.515e\-01 | TRUE    |
| Blautia.Otu0620                              | 8.4327   | \-0.024512     | 1.0662 | \-0.022991 | 0.9816575 | 0.99738 | 8.4327     | 4.323e\+02 | FALSE   | 4.159       | 12           | 8.953   | 4.310      | 8        | FALSE       | 4.310   | 2.77456    | 0.48988                                               | \-0.024512                              | 1.0366        | 1.1113                                                    | 1.0662                                      | 2.676588                 | 0.44080                                                              | \-0.022991                                             | 7.438e\-03            | 6.594e\-01                                                        | 9.817e\-01                                          | TRUE     | 17       | 182.72   | 3.676e\-01 | FALSE   |
| Bacteroides.Otu0775                          | 9.5710   | \-0.015703     | 1.1893 | \-0.013203 | 0.9894655 | 0.99738 | 9.5710     | 2.563e\+02 | FALSE   | 5.230       | 12           | 9.021   | 5.386      | 10       | FALSE       | 5.386   | 2.16925    | 1.47907                                               | \-0.015703                              | 1.1631        | 1.2441                                                    | 1.1893                                      | 1.865108                 | 1.18887                                                              | \-0.013203                                             | 6.217e\-02            | 2.345e\-01                                                        | 9.895e\-01                                          | TRUE     | 11       | 178.62   | 5.157e\-01 | FALSE   |
| Bacteroides.Otu1565                          | 1.1336   | \-0.014615     | 1.6277 | \-0.008979 | 0.9928358 | 0.99738 | 1.1336     | 5.366e\+00 | FALSE   | 8.694       | 9            | 15.816  | 9.371      | 9        | FALSE       | 9.371   | 0.61598    | \-0.61779                                             | \-0.014615                              | 1.5727        | 1.6897                                                    | 1.6277                                      | 0.391673                 | \-0.36561                                                            | \-0.008979                                             | 6.953e\-01            | 7.147e\-01                                                        | 9.928e\-01                                          | TRUE     | 10       | 85.56    | 3.864e\-01 | TRUE    |
| Bacteroides.Otu0006                          | 76.9647  | 0.003041       | 0.9269 | 0.003281   | 0.9973823 | 0.99738 | 76.9647    | 8.916e\+03 | FALSE   | 3.236       | 11           | 9.279   | 3.368      | 7        | FALSE       | 3.368   | 4.76152    | 1.95888                                               | 0.003041                                | 0.9000        | 0.9650                                                    | 0.9269                                      | 5.290805                 | 2.02991                                                              | 0.003281                                               | 1.218e\-07            | 4.237e\-02                                                        | 9.974e\-01                                          | TRUE     | 13       | 317.11   | 3.510e\-01 | FALSE   |
| Burkholderiales.Otu0023                      | 0.0000   | 0.000000       | 0.0000 | 0.000000   | 1.0000000 | NA      | 0.0000     | 0.000e\+00 | TRUE    | 33.000      | 100          | 10.579  | 33.000     | 8        | FALSE       | 33.000  | NA         | NA                                                    | NA                                      | NA            | NA                                                        | NA                                          | NA                       | NA                                                                   | NA                                                     | NA                    | NA                                                                | NA                                                  | NA       | NA       | NA       | 4.613e\-06 | TRUE    |





##### \(1.5.1.4.2.3\) Default transformations for further data analysis



Specific methods can override these and use their own normalization.


Count normalization method for data analysis (unless modified by specific methods) : [ drop.features:List of 1,  ..$ :"other", method.args  :List of 1,  ..$ theta:1, method       :"norm.ihs.prop"]


Wrote counts and metadata for raw counts Normalized after default transformations to files [`data/1.5.1.4.2.3-323a78d434samples.raw.16s.l.otu.count.tsv`](data/1.5.1.4.2.3-323a78d434samples.raw.16s.l.otu.count.tsv),[`data/1.5.1.4.2.3-323a78d434samples.raw.16s.l.otu.attr.tsv`](data/1.5.1.4.2.3-323a78d434samples.raw.16s.l.otu.attr.tsv)



##### \(1.5.1.4.3\) Ordinations, 

[`Subreport`](./1.5.1.4.3-report.html)